/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.io.FilenameFilter;

/**
 *
 * @author Ismael Ribeiro
 */
public class MENU_ORDEM_DE_SERVICO extends javax.swing.JInternalFrame {
    /**
     * Creates new form MENU_ORDEM_DE_SERVICO
     */
    public MENU_ORDEM_DE_SERVICO() {
        initComponents();
        //TEXTO_OS.setDocument(new LIMITE_DE_DIGITOS_ORDEM_DE_SERVICO(9));//9 é a quantidade de caracteres de uma os ex: F05064033
        TEXTO_OBS.setLineWrap(true);//QUEBRA AUTOMATICA DE LINHA 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        COMBO_TIPO = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        TEXTO_PRAZO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        COMBO_STATUS = new javax.swing.JComboBox();
        COMBO_DIA = new javax.swing.JComboBox();
        COMBO_MES = new javax.swing.JComboBox();
        COMBO_ANO = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEXTO_OBS = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        BOTAO_SALVAR = new javax.swing.JButton();
        TEXTO_OS = new javax.swing.JTextField();
        BOTAO_LOCALIZAR = new javax.swing.JButton();
        BOTAO_LIMPAR = new javax.swing.JButton();
        BOTAO_TESTE = new javax.swing.JButton();
        BOTAO_SAIR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Ordem de Serviço");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("OS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ENTRADA NO SISTEMA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("TIPO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        COMBO_TIPO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N", "P", "U", "G", "I", "E" }));
        getContentPane().add(COMBO_TIPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 45, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("PRAZO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        TEXTO_PRAZO.setEditable(false);
        getContentPane().add(TEXTO_PRAZO, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("STATUS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        COMBO_STATUS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OL", "SO", "PD", "OR", "OI", "OA" }));
        getContentPane().add(COMBO_STATUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 60, -1));

        COMBO_DIA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(COMBO_DIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 60, -1));

        COMBO_MES.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(COMBO_MES, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 60, -1));

        COMBO_ANO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016", "2015", "2014" }));
        getContentPane().add(COMBO_ANO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 70, -1));

        TEXTO_OBS.setColumns(20);
        TEXTO_OBS.setRows(5);
        jScrollPane1.setViewportView(TEXTO_OBS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 340, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("OBSERVAÇÕES");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        BOTAO_SALVAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/disquete.jpg"))); // NOI18N
        BOTAO_SALVAR.setBorder(null);
        BOTAO_SALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_SALVARActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_SALVAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        getContentPane().add(TEXTO_OS, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 10, 316, -1));

        BOTAO_LOCALIZAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icon-lupa.jpg"))); // NOI18N
        BOTAO_LOCALIZAR.setBorder(null);
        BOTAO_LOCALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_LOCALIZARActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_LOCALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        BOTAO_LIMPAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icon-borracha.jpg"))); // NOI18N
        BOTAO_LIMPAR.setBorder(null);
        BOTAO_LIMPAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_LIMPARActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_LIMPAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        BOTAO_TESTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icon-nuclear.png"))); // NOI18N
        BOTAO_TESTE.setBorder(null);
        BOTAO_TESTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_TESTEActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_TESTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        BOTAO_SAIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icone_sair.png"))); // NOI18N
        BOTAO_SAIR.setBorder(null);
        BOTAO_SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_SAIRActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_SAIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 340, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTAO_SALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_SALVARActionPerformed
        // TODO add your handling code here:
        
        java.io.File DIRETORIO = new java.io.File("C:\\PRODUCAO\\OS");
        DIRETORIO.mkdir();
        
        String OS = TEXTO_OS.getText();
        
        OS = OS.replace("/", "");
        
        if (!OS.equals(""))
        {
        
        OS = OS+".txt";
        
        File dir = new File("C:\\PRODUCAO\\OS");//LER
        
        File arq = new File(dir,OS);//LER
            try {
                FileReader fileReader = new FileReader(arq);//LER
                
                if (OS.equals(OS))
                {
                    //JOptionPane.showMessageDialog(null,"Este arquivo já existe ...");
                    Object[] options = { "Sim", "Não" };   
                 int opcao = JOptionPane.showOptionDialog(null,"Este arquivo já existe ..."
                 +"\ntem certeza que quer alterar os dados ?","Tem certeza ?"
                 ,JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);   
  
  
                 if (opcao != 0)    
                 {
                    //JOptionPane.showMessageDialog(null,"Você optou por não alterar as informações atuais.");
                    OS = "";
                 }   
                }
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MENU_ORDEM_DE_SERVICO.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        java.io.File arquivo = new java.io.File(DIRETORIO,OS );
        
        if (OS.equals("")){
        JOptionPane.showMessageDialog(null,"Nenhuma informação foi alterada !");    
        }
        else{
        JOptionPane.showMessageDialog(null,"Informação gravada com sucesso !");   
        }
        
        
        try {
            arquivo.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(MENU_ORDEM_DE_SERVICO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /////////////////////////
        String OBS;
        String DATA_DIA;
        String DATA_MES;
        String DATA_ANO;
        String TIPO_OS;
        String STATUS_OS;
        
        OBS = TEXTO_OBS.getText();
        DATA_DIA = (String) COMBO_DIA.getSelectedItem();
        DATA_MES = (String) COMBO_MES.getSelectedItem();
        DATA_ANO = (String) COMBO_ANO.getSelectedItem();
        TIPO_OS = (String) COMBO_TIPO.getSelectedItem();
        STATUS_OS = (String) COMBO_STATUS.getSelectedItem();
        
        
        FileWriter Obs = null;
        
        try {
            Obs = new FileWriter("C:\\PRODUCAO\\OS\\"+OS);
        } catch (IOException ex) {
            Logger.getLogger(MENU_ORDEM_DE_SERVICO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PrintWriter gravarArq = new PrintWriter(Obs); 
        {
              gravarArq.println(DATA_DIA);//LINHA DIA
              gravarArq.println(DATA_MES);//LINHA MES
              gravarArq.println(DATA_ANO);//LINHA ANO
              gravarArq.println(TIPO_OS);//LINHA TIPO DA OS
              gravarArq.println(STATUS_OS);//LINHA STATUS DA OS
              gravarArq.println(OBS);//LINHA OBSERVAÇÕES
        }
        try {
            Obs.close();
        } catch (IOException ex) {
            Logger.getLogger(MENU_ORDEM_DE_SERVICO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        
        BOTAO_LOCALIZARActionPerformed(evt);
        
        //else
        {
            if (OS.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Campos em branco ...");
        }
        }
    }//GEN-LAST:event_BOTAO_SALVARActionPerformed

    private void BOTAO_LOCALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_LOCALIZARActionPerformed
        //TODO add your handling code here:
        
        String OS = TEXTO_OS.getText();
        
        OS = OS.replace("/", "");
        
        if (OS.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Campos em branco ...");
        }
        
        OS = OS+".txt";
        
        File dir = new File("C:\\PRODUCAO\\OS");
        
        File arq = new File(dir,OS);//dir,OS
        
        try {
            FileReader fileReader = new FileReader(arq);
            
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            
             String DIA = bufferedReader.readLine();//DIA
             String MES = bufferedReader.readLine();//MÊS
             String ANO = bufferedReader.readLine();//ANO
             String TIPO_DA_OS = bufferedReader.readLine();//TIPO DA OS
             String STATUS_DA_OS = bufferedReader.readLine();//STATUS DA OS
             String OBSERVACOES = bufferedReader.readLine();//OBSERVAÇÕES
             
             DateFormat df = new SimpleDateFormat ("dd/MM/yyyy");
             df.setLenient(false);
            try {
                
                Date dataSistema = new Date();
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            
                Date d1 = df.parse (DIA+"/"+MES+"/"+ANO);
                Date d2 = df.parse (formato.format(dataSistema));
                
                long dt = (d2.getTime() - d1.getTime()) + 3600000;
                
                TEXTO_PRAZO.setText(""+dt / 86400000L);
                
            } catch (ParseException ex) {
                Logger.getLogger(MENU_ORDEM_DE_SERVICO.class.getName()).log(Level.SEVERE, null, ex);
            }
             
             int linha_1 = Integer.parseInt(DIA);
             int linha_2 = Integer.parseInt(MES);
             int linha_3 = Integer.parseInt(ANO);
             
             TEXTO_OBS.setText(OBSERVACOES);//DEFINE O TEXTO
             COMBO_DIA.setSelectedIndex(linha_1-1);//DEFINE O VALOR
             COMBO_MES.setSelectedIndex(linha_2-1);//DEFINE O VALOR
             COMBO_TIPO.setSelectedIndex(0);
             if (STATUS_DA_OS.equals("OL"))
             {
                 COMBO_STATUS.setSelectedIndex(0);
             }
             else
             if (STATUS_DA_OS.equals("SO"))
             {
                 COMBO_STATUS.setSelectedIndex(1);
             }
             else
             if (STATUS_DA_OS.equals("PD"))
             {
                 COMBO_STATUS.setSelectedIndex(2);
             }
             else
             if (STATUS_DA_OS.equals("OR"))
             {
                 COMBO_STATUS.setSelectedIndex(3);
             }
             else
             if (STATUS_DA_OS.equals("OI"))
             {
                 COMBO_STATUS.setSelectedIndex(4);
             }
             else
             if (STATUS_DA_OS.equals("OA"))
             {
                 COMBO_STATUS.setSelectedIndex(5);
             }
             ////////////////////////////////////
             if (ANO.equals("2014"))
             {
                 COMBO_ANO.setSelectedIndex(2);
             }
             else
             if (ANO.equals("2015"))
             {
                 COMBO_ANO.setSelectedIndex(1);
             }
             else
             if (ANO.equals("2016"))
             {
                 COMBO_ANO.setSelectedIndex(0);
             }
             
             if (TIPO_DA_OS.equals("N"))
             {
              COMBO_TIPO.setSelectedIndex(0);   
             }
             else
             if (TIPO_DA_OS.equals("P"))
             {
              COMBO_TIPO.setSelectedIndex(1);   
             }
             else
             if (TIPO_DA_OS.equals("U"))
             {
              COMBO_TIPO.setSelectedIndex(2);   
             }
             else
             if (TIPO_DA_OS.equals("G"))
             {
              COMBO_TIPO.setSelectedIndex(3);   
             }
             else
             if (TIPO_DA_OS.equals("I"))
             {
              COMBO_TIPO.setSelectedIndex(4);   
             }
             else
             if (TIPO_DA_OS.equals("E"))
             {
              COMBO_TIPO.setSelectedIndex(5);   
             }
             
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Ordem de serviço não encontrada ...");
            Logger.getLogger(MENU_ORDEM_DE_SERVICO.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MENU_ORDEM_DE_SERVICO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BOTAO_LOCALIZARActionPerformed

    private void BOTAO_LIMPARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_LIMPARActionPerformed
        //TODO add your handling code here:
        TEXTO_OBS.setText("");
        TEXTO_OS.setText("");
        TEXTO_PRAZO.setText("");
        COMBO_ANO.setSelectedIndex(0);
        COMBO_DIA.setSelectedIndex(0);
        COMBO_MES.setSelectedIndex(0);
        COMBO_STATUS.setSelectedIndex(0);
        COMBO_TIPO.setSelectedIndex(0);
    }//GEN-LAST:event_BOTAO_LIMPARActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }//GEN-LAST:event_formInternalFrameOpened

    private void BOTAO_TESTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_TESTEActionPerformed
        // TODO add your handling code here:
//        try {
//            Thread.sleep(10000);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(MENU_ORDEM_DE_SERVICO.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
        File diretorio = new File("C:\\PRODUCAO\\OS");
        
        String[] stringDir = diretorio.list();
        String[] stringDir2 = diretorio.list();
        
        int quantidade = diretorio.listFiles().length;
        
        for(int i = 0; i < 1; i++)
        {
              if ((stringDir[i].contains(".txt")) && (i == 0))
            {
                stringDir[i] = stringDir[i].replace(".txt", "");
                JOptionPane.showMessageDialog(null,"Você tem "+quantidade+" ordens de serviço salvas.");
            }
            else
            if (stringDir[i].contains(".txt"))
            {
                stringDir[i] = stringDir[i].replace(".txt", "");
                JOptionPane.showMessageDialog(null,""+(i)+"ª OS: "+stringDir[i-1]);
            }
        }
        
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        
        for(int j = 0; j < stringDir2[j].length(); j++)
        {
            if (stringDir2[j].contains(".txt"))
            {
                stringDir2[j] = stringDir2[j].replace(".txt", "");
                JOptionPane.showMessageDialog(null,""+(j+1)+"ª OS: "+stringDir2[j]);
            }
        }
        
    }//GEN-LAST:event_BOTAO_TESTEActionPerformed

    private void BOTAO_SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_SAIRActionPerformed
        // TODO add your handling code here:
        //application.exit();
        //System.exit(0);
        this.setVisible(false);
        //Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_BOTAO_SAIRActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAO_LIMPAR;
    private javax.swing.JButton BOTAO_LOCALIZAR;
    private javax.swing.JButton BOTAO_SAIR;
    private javax.swing.JButton BOTAO_SALVAR;
    private javax.swing.JButton BOTAO_TESTE;
    private javax.swing.JComboBox COMBO_ANO;
    private javax.swing.JComboBox COMBO_DIA;
    private javax.swing.JComboBox COMBO_MES;
    private javax.swing.JComboBox COMBO_STATUS;
    private javax.swing.JComboBox COMBO_TIPO;
    private javax.swing.JTextArea TEXTO_OBS;
    private javax.swing.JTextField TEXTO_OS;
    private javax.swing.JTextField TEXTO_PRAZO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
