/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Mael
 */
public class MENU_LOCALIZAR_COLABORADOR extends javax.swing.JInternalFrame {

    /**
     * Creates new form MENU_LOCALIZAR
     */
    public MENU_LOCALIZAR_COLABORADOR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TEXTO_BUSCA = new javax.swing.JTextField();
        BUSCA_ = new javax.swing.JLabel();
        TEXTO_RESULTADO = new javax.swing.JTextField();
        BOTAO_BUSCAR = new javax.swing.JButton();
        TEXTO_SETOR = new javax.swing.JTextField();
        BUSCA_1 = new javax.swing.JLabel();
        BOTAO_LIMPAR = new javax.swing.JButton();
        BOTAO_SAIR = new javax.swing.JButton();
        BUSCA_2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Localizar Colaborador");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(TEXTO_BUSCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 11, 298, -1));

        BUSCA_.setText("BUSCA:");
        getContentPane().add(BUSCA_, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 14, 50, -1));

        TEXTO_RESULTADO.setEditable(false);
        getContentPane().add(TEXTO_RESULTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 42, 298, -1));

        BOTAO_BUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icon-lupa.jpg"))); // NOI18N
        BOTAO_BUSCAR.setBorder(null);
        BOTAO_BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_BUSCARActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 113, -1, -1));

        TEXTO_SETOR.setEditable(false);
        getContentPane().add(TEXTO_SETOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 300, -1));

        BUSCA_1.setText("SETOR:");
        getContentPane().add(BUSCA_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, -1));

        BOTAO_LIMPAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icon-borracha.jpg"))); // NOI18N
        BOTAO_LIMPAR.setBorder(null);
        BOTAO_LIMPAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_LIMPARActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_LIMPAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 113, -1, -1));

        BOTAO_SAIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icone_sair.png"))); // NOI18N
        BOTAO_SAIR.setBorder(null);
        BOTAO_SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_SAIRActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_SAIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 113, -1, -1));

        BUSCA_2.setText("RESULTADO:");
        getContentPane().add(BUSCA_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTAO_BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_BUSCARActionPerformed
        // TODO add your handling code here:
        TECNICO ismael = new TECNICO();
        TECNICO glauber = new TECNICO();
        TECNICO paulo = new TECNICO();
        TECNICO bruno = new TECNICO();
        TECNICO julio = new TECNICO();
        TECNICO jociano = new TECNICO();
        TECNICO pedro = new TECNICO();
        TECNICO antonio = new TECNICO();
        TECNICO benedito = new TECNICO();
        TECNICO emmanuel = new TECNICO();
        TECNICO polibio = new TECNICO();
        TECNICO robson = new TECNICO();
        TECNICO lucas = new TECNICO();
        TECNICO alexsandro = new TECNICO();
        TECNICO rodrigo = new TECNICO();
        TECNICO edilberto = new TECNICO();
        TECNICO alexviana = new TECNICO();
        TECNICO henriqueestevao = new TECNICO();
        TECNICO joseairton = new TECNICO();
        TECNICO jeffersonratts = new TECNICO();
        TECNICO robertobarbosa = new TECNICO();
        TECNICO gilmarleysantos = new TECNICO();
        TECNICO alandouglas = new TECNICO();
        TECNICO williamsvictor = new TECNICO();
        TECNICO weslleyalves = new TECNICO();
        TECNICO francideniocarlos = new TECNICO();
        TECNICO randbrito = new TECNICO();
        TECNICO carolinasouza = new TECNICO();/////////////////
        TECNICO leandrolima = new TECNICO();
        TECNICO layanelima = new TECNICO();
        TECNICO samarasaraiva = new TECNICO();
        TECNICO patricialima = new TECNICO();
        TECNICO carlosrobsonrodriguesnunes = new TECNICO();
        TECNICO jessicanara = new TECNICO();
        TECNICO jessicacastro = new TECNICO();
        TECNICO henriquerodrigues = new TECNICO();
        TECNICO jonathanoliveira = new TECNICO();
        TECNICO raquelpadua = new TECNICO();
        TECNICO josecleber = new TECNICO();
        TECNICO henriquemoura = new TECNICO();
        TECNICO mariafreitas = new TECNICO();
        TECNICO gislianesoares = new TECNICO();
        TECNICO adelianeolimpio = new TECNICO();
        TECNICO thaiscosta = new TECNICO();
        TECNICO josetadeu = new TECNICO();
        TECNICO inaciomacedo = new TECNICO();
        TECNICO priscilasilva = new TECNICO();
        TECNICO danieledecarvalho = new TECNICO();
        TECNICO ericksammers = new TECNICO();
        TECNICO karlaalves = new TECNICO();

        //layane lima 2876-
        //samara saraiva 2865-
        //patricia lima 3024-
        //carlos robson rodrigues nunes 384173-
        //jessica nara 1924-
        //jessica castro 2874-
        //henrique rodrigues 2009-
        //jonathan oliveira 2220-
        //raquel padua 2650-
        //jose cleber 397-
        //henrique moura 3006-
        //maria freitas 1679-
        //gisliane soares 2537-
        //adeliane olimpio 2925-
        //thais costa 3027-
        //jose tadeu 2312-
        //inacio macedo 3077-
        //priscila silva 2239-
        //daniele de carvalho 1123 -
        //erick sammers 1997-
        //karla alves 980-
        
        ismael.nome = "ISMAEL";//SOBRENOME MOURA//
        glauber.nome = "GLAUBER";//PRIMEIRO NOME FRANCISCO//
        paulo.nome = "PAULO";//SOBRENOME HENRIQUE//
        bruno.nome = "BRUNO";//SOBRENOME FREITAS//
        julio.nome = "JULIO";//SOBRENOME FREITAS//
        jociano.nome = "JOCIANO";//SOBRENOME DIAS//
        pedro.nome = "PEDRO";//SOBRENOME JALES//
        antonio.nome = "ANTONIO";//SOBRENOME PAZ//
        benedito.nome = "BENEDITO";//SOBRENOME GOMES//
        emmanuel.nome = "EMMANUEL";//PRIMEIRO NOME JOSE//
        polibio.nome = "POLIBIO";//SOBRENOME LIMA//
        robson.nome = "ROBSON";//SOBRENOME NIELL//
        lucas.nome = "LUCAS";//SOBRENOME ALVES//
        alexsandro.nome = "ALEXSANDRO";//SOBRENOME SOUSA//
        rodrigo.nome = "RODRIGO";//SOBRENOME VIEIRA//
        edilberto.nome = "EDILBERTO";//SOBRENOME LIMA//
        alexviana.nome = "ALEX";//SOBRENOME VIANA//
        henriqueestevao.nome = "HENRIQUE";//ESTEVÃO//
        joseairton.nome = "AIRTON";//PRIMEIRO NOME AIRTON//
        jeffersonratts.nome = "JEFFERSON";//SOBRENOME RATTS//
        robertobarbosa.nome = "ROBERTO";//SOBRENOME BARBOSA
        gilmarleysantos.nome = "GIL";//SOBRENOME SANTOS
        alandouglas.nome = "ALAN";//SOBRENOME DOUGLAS
        williamsvictor.nome = "WILLIAMS";//SOBRENOME VICTOR
        weslleyalves.nome = "WESLLEY";//SOBRENOME ALVES
        francideniocarlos.nome = "FRANCIDENIO";//SOBRENOME CARLOS
        randbrito.nome = "RAND";//SOBRENOME BRITO
        carolinasouza.nome = "CAROLINA";//SOBRENOME SOUZA
        leandrolima.nome = "LEANDRO";//SOBRENOME LIMA
        
        ismael.em = 2228;
        String em_ismael = Integer.toString(ismael.em);
        glauber.em = 2378;
        String em_glauber = Integer.toString(glauber.em);
        paulo.em = 1152;
        String em_paulo = Integer.toString(paulo.em);
        bruno.em = 2940;
        String em_bruno = Integer.toString(bruno.em);
        julio.em = 1854;
        String em_julio = Integer.toString(julio.em);
        jociano.em = 983;
        String em_jociano = Integer.toString(jociano.em);
        antonio.em = 2732;
        String em_antonio = Integer.toString(antonio.em);
        benedito.em = 2127;
        String em_benedito = Integer.toString(benedito.em);
        emmanuel.em = 680;
        String em_emmanuel = Integer.toString(emmanuel.em);
        polibio.em = 1915;
        String em_polibio = Integer.toString(polibio.em);
        robson.em = 2283;
        String em_robson = Integer.toString(robson.em);
        lucas.em = 2742;
        String em_lucas = Integer.toString(lucas.em);
        alexsandro.em = 2964;
        String em_alexsandro = Integer.toString(alexsandro.em);
        rodrigo.em = 2942;
        String em_rodrigo = Integer.toString(rodrigo.em);
        edilberto.em = 776;
        String em_edilberto = Integer.toString(edilberto.em);
        alexviana.em = 2511;
        String em_alexviana = Integer.toString(alexviana.em);
        henriqueestevao.em = 2924;
        String em_henriqueestevao = Integer.toString(henriqueestevao.em);
        joseairton.em = 1115;
        String em_joseairton = Integer.toString(joseairton.em);
        jeffersonratts.em = 1813;
        String em_jeffersonratts = Integer.toString(jeffersonratts.em);
        robertobarbosa.em = 27;
        String em_robertobarbosa = Integer.toString(robertobarbosa.em);
        pedro.em = 2974;
        String em_pedro = Integer.toString(pedro.em);
        gilmarleysantos.em = 712;
        String em_gilmarleysantos = Integer.toString(gilmarleysantos.em);
        alandouglas.em = 917;
        String em_alandouglas = Integer.toString(alandouglas.em);
        williamsvictor.em = 175;
        String em_williamsvictor = Integer.toString(williamsvictor.em);
        weslleyalves.em = 3033;
        String em_weslleyalves = Integer.toString(weslleyalves.em);
        francideniocarlos.em = 241;
        String em_francideniocarlos = Integer.toString(francideniocarlos.em);
        randbrito.em = 2727;
        String em_randbrito = Integer.toString(randbrito.em);
        carolinasouza.em = 2764;
        String em_carolinasouza = Integer.toString(carolinasouza.em);
        leandrolima.em = 1463;
        String em_leandrolima = Integer.toString(leandrolima.em);
        
        if ((TEXTO_BUSCA.getText().equals(em_ismael)))
        {
            TEXTO_RESULTADO.setText(ismael.nome);
            TEXTO_SETOR.setText("ELETRONICA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(ismael.nome)) || (TEXTO_BUSCA.getText().equals("ismael")))
        {
            TEXTO_RESULTADO.setText(""+ismael.em);
            TEXTO_SETOR.setText("ELETRONICA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_glauber)))
        {
            TEXTO_RESULTADO.setText(glauber.nome);
            TEXTO_SETOR.setText("ELETRONICA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(glauber.nome)) || (TEXTO_BUSCA.getText().equals("glauber")))
        {
            TEXTO_RESULTADO.setText(""+glauber.em);
            TEXTO_SETOR.setText("ELETRONICA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_paulo)))
        {
            TEXTO_RESULTADO.setText(paulo.nome);
            TEXTO_SETOR.setText("ELETRONICA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(paulo.nome)) || (TEXTO_BUSCA.getText().equals("paulo")))
        {
            TEXTO_RESULTADO.setText(""+paulo.em);
            TEXTO_SETOR.setText("ELETRONICA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_bruno)))
        {
            TEXTO_RESULTADO.setText(bruno.nome);
            TEXTO_SETOR.setText("NOTEBOOK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(bruno.nome)) || (TEXTO_BUSCA.getText().equals("bruno")))
        {
            TEXTO_RESULTADO.setText(""+bruno.em);
            TEXTO_SETOR.setText("NOTEBOOK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_julio)))
        {
            TEXTO_RESULTADO.setText(julio.nome);
            TEXTO_SETOR.setText("IMPRESSORAS");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(julio.nome)) || (TEXTO_BUSCA.getText().equals("julio")))
        {
            TEXTO_RESULTADO.setText(""+julio.em);
            TEXTO_SETOR.setText("IMPRESSORAS");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_jociano)))
        {
            TEXTO_RESULTADO.setText(jociano.nome);
            TEXTO_SETOR.setText("RECARGA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(jociano.nome)) || (TEXTO_BUSCA.getText().equals("jociano")))
        {
            TEXTO_RESULTADO.setText(""+jociano.em);
            TEXTO_SETOR.setText("RECARGA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_pedro)))
        {
            TEXTO_RESULTADO.setText(pedro.nome);
            TEXTO_SETOR.setText("NOTEBOOK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(pedro.nome)) || (TEXTO_BUSCA.getText().equals("pedro")))
        {
            TEXTO_RESULTADO.setText(""+pedro.em);
            TEXTO_SETOR.setText("NOTEBOOK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_antonio)))
        {
            TEXTO_RESULTADO.setText(antonio.nome);
            TEXTO_SETOR.setText("TABLET");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(antonio.nome)) || (TEXTO_BUSCA.getText().equals("antonio")))
        {
            TEXTO_RESULTADO.setText(""+antonio.em);
            TEXTO_SETOR.setText("TABLET");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_benedito)))
        {
            TEXTO_RESULTADO.setText(benedito.nome);
            TEXTO_SETOR.setText("NOTEBOOK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(benedito.nome)) || (TEXTO_BUSCA.getText().equals("benedito")))
        {
            TEXTO_RESULTADO.setText(""+benedito.em);
            TEXTO_SETOR.setText("NOTEBOOK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_emmanuel)))
        {
            TEXTO_RESULTADO.setText(emmanuel.nome);
            TEXTO_SETOR.setText("GARANTIA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(emmanuel.nome)) || (TEXTO_BUSCA.getText().equals("emmanuel")))
        {
            TEXTO_RESULTADO.setText(""+emmanuel.em);
            TEXTO_SETOR.setText("GARANTIA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_polibio)))
        {
            TEXTO_RESULTADO.setText(polibio.nome);
            TEXTO_SETOR.setText("LAUDO");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(polibio.nome)) || (TEXTO_BUSCA.getText().equals("polibio")))
        {
            TEXTO_RESULTADO.setText(""+polibio.em);
            TEXTO_SETOR.setText("LAUDO");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_robson)))
        {
            TEXTO_RESULTADO.setText(robson.nome);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(robson.nome)) || (TEXTO_BUSCA.getText().equals("robson")))
        {
            TEXTO_RESULTADO.setText(""+robson.em);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_lucas)))
        {
            TEXTO_RESULTADO.setText(lucas.nome);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(lucas.nome)) || (TEXTO_BUSCA.getText().equals("lucas")))
        {
            TEXTO_RESULTADO.setText(""+lucas.em);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_alexsandro)))
        {
            TEXTO_RESULTADO.setText(alexsandro.nome);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(alexsandro.nome)) || (TEXTO_BUSCA.getText().equals("alexsandro")))
        {
            TEXTO_RESULTADO.setText(""+alexsandro.em);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_rodrigo)))
        {
            TEXTO_RESULTADO.setText(rodrigo.nome);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(rodrigo.nome)) || (TEXTO_BUSCA.getText().equals("rodrigo")))
        {
            TEXTO_RESULTADO.setText(""+rodrigo.em);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_edilberto)))
        {
            TEXTO_RESULTADO.setText(edilberto.nome);
            TEXTO_SETOR.setText("GARANTIA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(edilberto.nome)) || (TEXTO_BUSCA.getText().equals("edilberto")))
        {
            TEXTO_RESULTADO.setText(""+edilberto.em);
            TEXTO_SETOR.setText("GARANTIA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_alexviana)))
        {
            TEXTO_RESULTADO.setText(alexviana.nome);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(alexviana.nome)) || (TEXTO_BUSCA.getText().equals("alex")))
        {
            TEXTO_RESULTADO.setText(""+alexviana.em);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_henriqueestevao)))
        {
            TEXTO_RESULTADO.setText(henriqueestevao.nome);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(henriqueestevao.nome)) || (TEXTO_BUSCA.getText().equals("henrique")))
        {
            TEXTO_RESULTADO.setText(""+henriqueestevao.em);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_joseairton)))
        {
            TEXTO_RESULTADO.setText(joseairton.nome);
            TEXTO_SETOR.setText("NOTEBOOK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(joseairton.nome)) || (TEXTO_BUSCA.getText().equals("airton")))
        {
            TEXTO_RESULTADO.setText(""+joseairton.em);
            TEXTO_SETOR.setText("NOTEBOOK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_jeffersonratts)))
        {
            TEXTO_RESULTADO.setText(jeffersonratts.nome);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(jeffersonratts.nome)) || (TEXTO_BUSCA.getText().equals("jefferson")))
        {
            TEXTO_RESULTADO.setText(""+jeffersonratts.em);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_robertobarbosa)))
        {
            TEXTO_RESULTADO.setText(robertobarbosa.nome);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(robertobarbosa.nome)) || (TEXTO_BUSCA.getText().equals("roberto")))
        {
            TEXTO_RESULTADO.setText(""+robertobarbosa.em);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_gilmarleysantos)))
        {
            TEXTO_RESULTADO.setText(gilmarleysantos.nome);
            TEXTO_SETOR.setText("GESTAO");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(gilmarleysantos.nome)) || (TEXTO_BUSCA.getText().equals("gil")))
        {
            TEXTO_RESULTADO.setText(""+gilmarleysantos.em);
            TEXTO_SETOR.setText("GESTAO");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_alandouglas)))
        {
            TEXTO_RESULTADO.setText(alandouglas.nome);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(alandouglas.nome)) || (TEXTO_BUSCA.getText().equals("alan")) || (TEXTO_BUSCA.getText().equals("piani")) || (TEXTO_BUSCA.getText().equals("PIANI")))
        {
            TEXTO_RESULTADO.setText(""+alandouglas.em);
            TEXTO_SETOR.setText("DESK");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_williamsvictor)))
        {
            TEXTO_RESULTADO.setText(williamsvictor.nome);
            TEXTO_SETOR.setText("RMA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(williamsvictor.nome)) || (TEXTO_BUSCA.getText().equals("williams")))
        {
            TEXTO_RESULTADO.setText(""+williamsvictor.em);
            TEXTO_SETOR.setText("RMA");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_weslleyalves)))
        {
            TEXTO_RESULTADO.setText(weslleyalves.nome);
            TEXTO_SETOR.setText("CHECKLIST");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(weslleyalves.nome)) || (TEXTO_BUSCA.getText().equals("weslley")))
        {
            TEXTO_RESULTADO.setText(""+weslleyalves.em);
            TEXTO_SETOR.setText("CHECK LIST");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_francideniocarlos)))
        {
            TEXTO_RESULTADO.setText(francideniocarlos.nome);
            TEXTO_SETOR.setText("INSPEÇÃO");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(francideniocarlos.nome)) || (TEXTO_BUSCA.getText().equals("francidenio")) || (TEXTO_BUSCA.getText().equals("sidenio")))
        {
            TEXTO_RESULTADO.setText(""+francideniocarlos.em);
            TEXTO_SETOR.setText("INSPEÇÃO");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_randbrito)))
        {
            TEXTO_RESULTADO.setText(randbrito.nome);
            TEXTO_SETOR.setText("COTAÇÃO");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(randbrito.nome)) || (TEXTO_BUSCA.getText().equals("rand")))
        {
            TEXTO_RESULTADO.setText(""+randbrito.em);
            TEXTO_SETOR.setText("COTAÇÃO");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_carolinasouza)))
        {
            TEXTO_RESULTADO.setText(carolinasouza.nome);
            TEXTO_SETOR.setText("RECEPÇÃO");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(carolinasouza.nome)) || (TEXTO_BUSCA.getText().equals("carolina")))
        {
            TEXTO_RESULTADO.setText(""+carolinasouza.em);
            TEXTO_SETOR.setText("RECEPÇÃO");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(em_leandrolima)))
        {
            TEXTO_RESULTADO.setText(leandrolima.nome);
            TEXTO_SETOR.setText("");
        }
        else
        if ((TEXTO_BUSCA.getText().equals(leandrolima.nome)) || (TEXTO_BUSCA.getText().equals("leandro")))
        {
            TEXTO_RESULTADO.setText(""+leandrolima.em);
            TEXTO_SETOR.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Busca inválida ...");
        }
    }//GEN-LAST:event_BOTAO_BUSCARActionPerformed

    private void BOTAO_LIMPARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_LIMPARActionPerformed
        // TODO add your handling code here:
        TEXTO_BUSCA.setText("");
        TEXTO_SETOR.setText("");
        TEXTO_RESULTADO.setText("");
    }//GEN-LAST:event_BOTAO_LIMPARActionPerformed

    private void BOTAO_SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_SAIRActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BOTAO_SAIRActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAO_BUSCAR;
    private javax.swing.JButton BOTAO_LIMPAR;
    private javax.swing.JButton BOTAO_SAIR;
    private javax.swing.JLabel BUSCA_;
    private javax.swing.JLabel BUSCA_1;
    private javax.swing.JLabel BUSCA_2;
    private javax.swing.JTextField TEXTO_BUSCA;
    private javax.swing.JTextField TEXTO_RESULTADO;
    private javax.swing.JTextField TEXTO_SETOR;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
