/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Mael
 */
public class MENU_F4 extends javax.swing.JInternalFrame {

    /**
     * Creates new form MENU_TESTE
     */
    public MENU_F4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        COMBO_EM = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Lista de EM");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(COMBO_EM, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(COMBO_EM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    //COMBO_EM.setToolTipText("ismael");
    
    TECNICO ismael = new TECNICO();
        TECNICO glauber = new TECNICO();
        TECNICO paulo = new TECNICO();
        TECNICO bruno = new TECNICO();
        TECNICO julio = new TECNICO();
        TECNICO jociano = new TECNICO();
        TECNICO pedro = new TECNICO();
        TECNICO antonio = new TECNICO();
        TECNICO benedito = new TECNICO();
        TECNICO emmanuel = new TECNICO();
        TECNICO polibio = new TECNICO();
        TECNICO robson = new TECNICO();
        TECNICO lucas = new TECNICO();
        TECNICO alexsandro = new TECNICO();
        TECNICO rodrigo = new TECNICO();
        TECNICO edilberto = new TECNICO();
        TECNICO alexviana = new TECNICO();
        TECNICO henriqueestevao = new TECNICO();
        TECNICO joseairton = new TECNICO();
        TECNICO jeffersonratts = new TECNICO();
        TECNICO robertobarbosa = new TECNICO();
        TECNICO gilmarleysantos = new TECNICO();
        TECNICO alandouglas = new TECNICO();
        TECNICO williamsvictor = new TECNICO();
        TECNICO weslleyalves = new TECNICO();
        TECNICO francideniocarlos = new TECNICO();
        TECNICO randbrito = new TECNICO();
        TECNICO carolinasouza = new TECNICO();/////////////////
        TECNICO leandrolima = new TECNICO();
        TECNICO layanelima = new TECNICO();
        TECNICO samarasaraiva = new TECNICO();
        TECNICO patricialima = new TECNICO();
        TECNICO carlosrobsonrodriguesnunes = new TECNICO();
        TECNICO jessicanara = new TECNICO();
        TECNICO jessicacastro = new TECNICO();
        TECNICO henriquerodrigues = new TECNICO();
        TECNICO jonathanoliveira = new TECNICO();
        TECNICO raquelpadua = new TECNICO();
        TECNICO josecleber = new TECNICO();
        TECNICO henriquemoura = new TECNICO();
        TECNICO mariafreitas = new TECNICO();
        TECNICO gislianesoares = new TECNICO();
        TECNICO adelianeolimpio = new TECNICO();
        TECNICO thaiscosta = new TECNICO();
        TECNICO josetadeu = new TECNICO();
        TECNICO inaciomacedo = new TECNICO();
        TECNICO priscilasilva = new TECNICO();
        TECNICO danieledecarvalho = new TECNICO();
        TECNICO ericksammers = new TECNICO();
        TECNICO karlaalves = new TECNICO();

        //layane lima 2876-
        //samara saraiva 2865-
        //patricia lima 3024-
        //carlos robson rodrigues nunes 384173-
        //jessica nara 1924-
        //jessica castro 2874-
        //henrique rodrigues 2009-
        //jonathan oliveira 2220-
        //raquel padua 2650-
        //jose cleber 397-
        //henrique moura 3006-
        //maria freitas 1679-
        //gisliane soares 2537-
        //adeliane olimpio 2925-
        //thais costa 3027-
        //jose tadeu 2312-
        //inacio macedo 3077-
        //priscila silva 2239-
        //daniele de carvalho 1123 -
        //erick sammers 1997-
        //karla alves 980-
        
        ismael.nome = "ISMAEL";//SOBRENOME MOURA//
        glauber.nome = "GLAUBER";//PRIMEIRO NOME FRANCISCO//
        paulo.nome = "PAULO";//SOBRENOME HENRIQUE//
        bruno.nome = "BRUNO";//SOBRENOME FREITAS//
        julio.nome = "JULIO";//SOBRENOME FREITAS//
        jociano.nome = "JOCIANO";//SOBRENOME DIAS//
        pedro.nome = "PEDRO";//SOBRENOME JALES//
        antonio.nome = "ANTONIO";//SOBRENOME PAZ//
        benedito.nome = "BENEDITO";//SOBRENOME GOMES//
        emmanuel.nome = "EMMANUEL";//PRIMEIRO NOME JOSE//
        polibio.nome = "POLIBIO";//SOBRENOME LIMA//
        robson.nome = "ROBSON";//SOBRENOME NIELL//
        lucas.nome = "LUCAS";//SOBRENOME ALVES//
        alexsandro.nome = "ALEXSANDRO";//SOBRENOME SOUSA//
        rodrigo.nome = "RODRIGO";//SOBRENOME VIEIRA//
        edilberto.nome = "EDILBERTO";//SOBRENOME LIMA//
        alexviana.nome = "ALEX";//SOBRENOME VIANA//
        henriqueestevao.nome = "HENRIQUE";//ESTEVÃO//
        joseairton.nome = "AIRTON";//PRIMEIRO NOME AIRTON//
        jeffersonratts.nome = "JEFFERSON";//SOBRENOME RATTS//
        robertobarbosa.nome = "ROBERTO";//SOBRENOME BARBOSA
        gilmarleysantos.nome = "GIL";//SOBRENOME SANTOS
        alandouglas.nome = "ALAN";//SOBRENOME DOUGLAS
        williamsvictor.nome = "WILLIAMS";//SOBRENOME VICTOR
        weslleyalves.nome = "WESLLEY";//SOBRENOME ALVES
        francideniocarlos.nome = "FRANCIDENIO";//SOBRENOME CARLOS
        randbrito.nome = "RAND";//SOBRENOME BRITO
        carolinasouza.nome = "CAROLINA";//SOBRENOME SOUZA
        leandrolima.nome = "LEANDRO";//SOBRENOME LIMA
        
        ismael.em = 2228;
        String em_ismael = Integer.toString(ismael.em);
        glauber.em = 2378;
        String em_glauber = Integer.toString(glauber.em);
        paulo.em = 1152;
        String em_paulo = Integer.toString(paulo.em);
        bruno.em = 2940;
        String em_bruno = Integer.toString(bruno.em);
        julio.em = 1854;
        String em_julio = Integer.toString(julio.em);
        jociano.em = 983;
        String em_jociano = Integer.toString(jociano.em);
        antonio.em = 2732;
        String em_antonio = Integer.toString(antonio.em);
        benedito.em = 2127;
        String em_benedito = Integer.toString(benedito.em);
        emmanuel.em = 680;
        String em_emmanuel = Integer.toString(emmanuel.em);
        polibio.em = 1915;
        String em_polibio = Integer.toString(polibio.em);
        robson.em = 2283;
        String em_robson = Integer.toString(robson.em);
        lucas.em = 2742;
        String em_lucas = Integer.toString(lucas.em);
        alexsandro.em = 2964;
        String em_alexsandro = Integer.toString(alexsandro.em);
        rodrigo.em = 2942;
        String em_rodrigo = Integer.toString(rodrigo.em);
        edilberto.em = 776;
        String em_edilberto = Integer.toString(edilberto.em);
        alexviana.em = 2511;
        String em_alexviana = Integer.toString(alexviana.em);
        henriqueestevao.em = 2924;
        String em_henriqueestevao = Integer.toString(henriqueestevao.em);
        joseairton.em = 1115;
        String em_joseairton = Integer.toString(joseairton.em);
        jeffersonratts.em = 1813;
        String em_jeffersonratts = Integer.toString(jeffersonratts.em);
        robertobarbosa.em = 27;
        String em_robertobarbosa = Integer.toString(robertobarbosa.em);
        pedro.em = 2974;
        String em_pedro = Integer.toString(pedro.em);
        gilmarleysantos.em = 712;
        String em_gilmarleysantos = Integer.toString(gilmarleysantos.em);
        alandouglas.em = 917;
        String em_alandouglas = Integer.toString(alandouglas.em);
        williamsvictor.em = 175;
        String em_williamsvictor = Integer.toString(williamsvictor.em);
        weslleyalves.em = 3033;
        String em_weslleyalves = Integer.toString(weslleyalves.em);
        francideniocarlos.em = 241;
        String em_francideniocarlos = Integer.toString(francideniocarlos.em);
        randbrito.em = 2727;
        String em_randbrito = Integer.toString(randbrito.em);
        carolinasouza.em = 2764;
        String em_carolinasouza = Integer.toString(carolinasouza.em);
        leandrolima.em = 1463;
        String em_leandrolima = Integer.toString(leandrolima.em);
    
    COMBO_EM.addItem(ismael.nome+" "+em_ismael);
    COMBO_EM.addItem(glauber.nome+" "+em_glauber);
    COMBO_EM.addItem(paulo.nome+" "+em_paulo);
    COMBO_EM.addItem(bruno.nome+" "+em_bruno);
    COMBO_EM.addItem(julio.nome+" "+em_julio);
    COMBO_EM.addItem(jociano.nome+" "+em_jociano);
    COMBO_EM.addItem(antonio.nome+" "+em_antonio);
    COMBO_EM.addItem(benedito.nome+" "+em_benedito);
    COMBO_EM.addItem(emmanuel.nome+" "+em_emmanuel);
    COMBO_EM.addItem(polibio.nome+" "+em_polibio);
    COMBO_EM.addItem(robson.nome+" "+em_robson);
    COMBO_EM.addItem(lucas.nome+" "+em_lucas);
    COMBO_EM.addItem(alexsandro.nome+" "+em_alexsandro);
    COMBO_EM.addItem(rodrigo.nome+" "+em_rodrigo);
    COMBO_EM.addItem(edilberto.nome+" "+em_edilberto);
    COMBO_EM.addItem(alexviana.nome+" "+em_alexviana);
    COMBO_EM.addItem(henriqueestevao.nome+" "+em_henriqueestevao);
    COMBO_EM.addItem(joseairton.nome+" "+em_joseairton);
    COMBO_EM.addItem(jeffersonratts.nome+" "+em_jeffersonratts);
    COMBO_EM.addItem(robertobarbosa.nome+" "+em_robertobarbosa);
    COMBO_EM.addItem(pedro.nome+" "+em_pedro);
    COMBO_EM.addItem(gilmarleysantos.nome+" "+em_gilmarleysantos);
    COMBO_EM.addItem(alandouglas.nome+" "+em_alandouglas);
    COMBO_EM.addItem(williamsvictor.nome+" "+em_williamsvictor);
    COMBO_EM.addItem(weslleyalves.nome+" "+em_weslleyalves);
    COMBO_EM.addItem(francideniocarlos.nome+" "+em_francideniocarlos);
    COMBO_EM.addItem(randbrito.nome+" "+em_randbrito);
    COMBO_EM.addItem(carolinasouza.nome+" "+em_carolinasouza);
    COMBO_EM.addItem(leandrolima.nome+" "+em_leandrolima);
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox COMBO_EM;
    // End of variables declaration//GEN-END:variables
}
