/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Ismael Ribeiro
 */
public class MENU_PRODUCAO extends javax.swing.JInternalFrame {
    
    public ELETRONICA eletronica;
    public NOTEBOOK notebook;
    public DATA data;
    public GARANTIA garantia;
    public DESKTOP desktop;
    public RECARGA recarga;
    public IMPRESSORA impressora;
    public TABLET tablet;
    public LAUDO laudo;
    public RECEPCAO recepcao;
    public INDICADOR indicador;
    public TECNICO tecnico;
    
    public static String em;
    public static String total_de_ol;
    public static String porcentagem_de_producao;
    public static String nome;
    public static String setor;
    public static String porcentagem_dia_base;
    
    /**
     * Creates new form 
     */
    public MENU_PRODUCAO() {
        
        eletronica = new ELETRONICA();
        notebook = new NOTEBOOK();
        data = new DATA();
        garantia = new GARANTIA();
        desktop = new DESKTOP();
        recarga = new RECARGA();
        impressora = new IMPRESSORA();
        tablet = new TABLET();
        laudo = new LAUDO();
        recepcao = new RECEPCAO();
        indicador = new INDICADOR();
        tecnico = new TECNICO();
        
        initComponents();
        //TEXTO_EM.setDocument(new LIMITE_DE_DIGITOS_EM(4));//Limite de um EM ex: 2228//---------------
        //TEXTO_TOTAL_OL.setDocument(new LIMITE_DE_DIGITOS_EM(3));//COM ESSA LINHA DEU ERRO NA CONTAGEM ... :/
        //TEXTO_OL_DO_DIA.setDocument(new LIMITE_DE_DIGITOS_EM(3));//-----------------
        
        data.Data_Automatica(""+data.dia_do_ano);//DEFINE O DIA BASE ATRAVES DO ARQUIVO TXT
        data.Dia_Atual(data.dia);//DEFINE O DIA BASE ATRAVES DO ARQUIVO TXT
        
        BOTAO_SALVAR.setToolTipText("Salvar");//MOSTRA UM TEXTO AO PASSAR MOUSE EM CIMA
        BOTAO_SAIR.setToolTipText("Sair");
        BOTAO_ATUAL.setToolTipText("Atual");
        BOTAO_OL_DO_DIA.setToolTipText("OL");
        BOTAO_PADRAO.setToolTipText("Padrão");
        BOTAO_LIMPAR.setToolTipText("Limpar");
        BOTAO_RESULTADO.setToolTipText("Resultado");
        DIABASE_.setText("DIA BASE "+data.DIA_BASE+"/ "+data.MES_VALIDO_ABREVIADO);
    }
    
    public void Arquivo(){
        File dir = new File("C:\\PRODUCAO\\");

        File arq = new File(dir,"TECNICO.txt");
        
        try {
        
        FileReader fileReader = new FileReader(arq);
        BufferedReader bufferedReader = new BufferedReader(fileReader);
        
            try {
                
                em = bufferedReader.readLine();
                total_de_ol = bufferedReader.readLine();
                porcentagem_de_producao = bufferedReader.readLine();
                nome = bufferedReader.readLine();
                setor = bufferedReader.readLine();
                porcentagem_dia_base = bufferedReader.readLine();
                
            } catch (IOException ex) {
                Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        } catch (FileNotFoundException ex) {
        Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        TEXTO_TOTAL_OL = new javax.swing.JTextField();
        BOTAO_RESULTADO = new javax.swing.JButton();
        TEXTO_PROJETADO = new javax.swing.JTextField();
        TOTALDEOL = new javax.swing.JLabel();
        PROJETADO_ = new javax.swing.JLabel();
        EM_ = new javax.swing.JLabel();
        TEXTO_NOME = new javax.swing.JTextField();
        TEXTO_FALTA = new javax.swing.JTextField();
        FALTA_ = new javax.swing.JLabel();
        PREVISTO_ = new javax.swing.JLabel();
        TEXTO_PREVISTO = new javax.swing.JTextField();
        DIFERENCAGERAL = new javax.swing.JLabel();
        TEXTO_DIFERENCA_GERAL = new javax.swing.JTextField();
        DIASUTEIS = new javax.swing.JLabel();
        TEXTO_DIAS_UTEIS = new javax.swing.JTextField();
        DIABASE_ = new javax.swing.JLabel();
        TEXTO_DIA_BASE = new javax.swing.JTextField();
        NOME_ = new javax.swing.JLabel();
        TEXTO_EM = new javax.swing.JTextField();
        BOTAO_SAIR = new javax.swing.JButton();
        TEXTO_SETOR = new javax.swing.JTextField();
        SETOR_ = new javax.swing.JLabel();
        TEXTO_DIAS_UTEIS_RESTANTES = new javax.swing.JTextField();
        DIASUTEIS1 = new javax.swing.JLabel();
        OPCAO_PRODUCAO_ATUAL = new javax.swing.JCheckBox();
        BOTAO_SALVAR = new javax.swing.JButton();
        BOTAO_ATUAL = new javax.swing.JButton();
        OLDODIA = new javax.swing.JLabel();
        TEXTO_OL_DO_DIA = new javax.swing.JTextField();
        TEXTO_DIFERENCA_DIARIA = new javax.swing.JTextField();
        TOTALDEOL2 = new javax.swing.JLabel();
        BOTAO_OL_DO_DIA = new javax.swing.JButton();
        BOTAO_LIMPAR = new javax.swing.JButton();
        MEDIA_DIARIA_ = new javax.swing.JLabel();
        TEXTO_MEDIA_DIARIA = new javax.swing.JTextField();
        BOTAO_PADRAO = new javax.swing.JButton();
        COMBO_DIA = new javax.swing.JComboBox();
        OPCAO_DEFINIR_DIA = new javax.swing.JCheckBox();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setClosable(true);
        setIconifiable(true);
        setTitle("Relatório de Acompanhamento de Metas Diário - Dezembro 2015");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icone-calculadora.gif"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TEXTO_TOTAL_OL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO_TOTAL_OLActionPerformed(evt);
            }
        });
        getContentPane().add(TEXTO_TOTAL_OL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 269, -1));

        BOTAO_RESULTADO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icon-resultado.gif"))); // NOI18N
        BOTAO_RESULTADO.setBorder(null);
        BOTAO_RESULTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_RESULTADOActionPerformed(evt);
            }
        });
        BOTAO_RESULTADO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BOTAO_RESULTADOKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BOTAO_RESULTADOKeyTyped(evt);
            }
        });
        getContentPane().add(BOTAO_RESULTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        TEXTO_PROJETADO.setEditable(false);
        TEXTO_PROJETADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO_PROJETADOActionPerformed(evt);
            }
        });
        getContentPane().add(TEXTO_PROJETADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 269, -1));

        TOTALDEOL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TOTALDEOL.setText("TOTAL DE OL");
        getContentPane().add(TOTALDEOL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 20));

        PROJETADO_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PROJETADO_.setText("PROJETADO");
        getContentPane().add(PROJETADO_, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, 20));

        EM_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EM_.setText("EM:");
        getContentPane().add(EM_, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 27, 20));

        TEXTO_NOME.setEditable(false);
        TEXTO_NOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO_NOMEActionPerformed(evt);
            }
        });
        getContentPane().add(TEXTO_NOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 269, -1));

        TEXTO_FALTA.setEditable(false);
        TEXTO_FALTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO_FALTAActionPerformed(evt);
            }
        });
        getContentPane().add(TEXTO_FALTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 269, -1));

        FALTA_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FALTA_.setText("FALTA");
        getContentPane().add(FALTA_, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 20));

        PREVISTO_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PREVISTO_.setText("PREVISTO");
        getContentPane().add(PREVISTO_, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 20));

        TEXTO_PREVISTO.setEditable(false);
        TEXTO_PREVISTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO_PREVISTOActionPerformed(evt);
            }
        });
        getContentPane().add(TEXTO_PREVISTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 269, -1));

        DIFERENCAGERAL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DIFERENCAGERAL.setText("DIFERENÇA GERAL");
        getContentPane().add(DIFERENCAGERAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 20));

        TEXTO_DIFERENCA_GERAL.setEditable(false);
        TEXTO_DIFERENCA_GERAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO_DIFERENCA_GERALActionPerformed(evt);
            }
        });
        getContentPane().add(TEXTO_DIFERENCA_GERAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 269, -1));

        DIASUTEIS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DIASUTEIS.setText("DIAS ÚTEIS");
        getContentPane().add(DIASUTEIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, 20));

        TEXTO_DIAS_UTEIS.setEditable(false);
        TEXTO_DIAS_UTEIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO_DIAS_UTEISActionPerformed(evt);
            }
        });
        getContentPane().add(TEXTO_DIAS_UTEIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 269, -1));

        DIABASE_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DIABASE_.setText("DIA BASE 07/ DEZ");
        getContentPane().add(DIABASE_, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, 20));

        TEXTO_DIA_BASE.setEditable(false);
        TEXTO_DIA_BASE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO_DIA_BASEActionPerformed(evt);
            }
        });
        getContentPane().add(TEXTO_DIA_BASE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 269, -1));

        NOME_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NOME_.setText("NOME");
        getContentPane().add(NOME_, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 20));

        TEXTO_EM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO_EMActionPerformed(evt);
            }
        });
        getContentPane().add(TEXTO_EM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 269, -1));

        BOTAO_SAIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icone_sair.png"))); // NOI18N
        BOTAO_SAIR.setBorder(null);
        BOTAO_SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_SAIRActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_SAIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        TEXTO_SETOR.setEditable(false);
        TEXTO_SETOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO_SETORActionPerformed(evt);
            }
        });
        getContentPane().add(TEXTO_SETOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 269, -1));

        SETOR_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SETOR_.setText("SETOR");
        getContentPane().add(SETOR_, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 20));

        TEXTO_DIAS_UTEIS_RESTANTES.setEditable(false);
        TEXTO_DIAS_UTEIS_RESTANTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO_DIAS_UTEIS_RESTANTESActionPerformed(evt);
            }
        });
        getContentPane().add(TEXTO_DIAS_UTEIS_RESTANTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 269, -1));

        DIASUTEIS1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DIASUTEIS1.setText("DIAS ÚTEIS RESTANTES");
        getContentPane().add(DIASUTEIS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 20));

        OPCAO_PRODUCAO_ATUAL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OPCAO_PRODUCAO_ATUAL.setText("PRODUÇÃO ATUAL");
        OPCAO_PRODUCAO_ATUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPCAO_PRODUCAO_ATUALActionPerformed(evt);
            }
        });
        getContentPane().add(OPCAO_PRODUCAO_ATUAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        BOTAO_SALVAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/disquete.jpg"))); // NOI18N
        BOTAO_SALVAR.setBorder(null);
        BOTAO_SALVAR.setEnabled(false);
        BOTAO_SALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_SALVARActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_SALVAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        BOTAO_ATUAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icone_estrela.png"))); // NOI18N
        BOTAO_ATUAL.setBorder(null);
        BOTAO_ATUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_ATUALActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_ATUAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        OLDODIA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OLDODIA.setText("OL DO DIA");
        getContentPane().add(OLDODIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 20));
        getContentPane().add(TEXTO_OL_DO_DIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 269, -1));

        TEXTO_DIFERENCA_DIARIA.setEditable(false);
        getContentPane().add(TEXTO_DIFERENCA_DIARIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 269, -1));

        TOTALDEOL2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TOTALDEOL2.setText("DIFERENÇA DIÁRIA");
        getContentPane().add(TOTALDEOL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        BOTAO_OL_DO_DIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icon_trofeu.gif"))); // NOI18N
        BOTAO_OL_DO_DIA.setBorder(null);
        BOTAO_OL_DO_DIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_OL_DO_DIAActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_OL_DO_DIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        BOTAO_LIMPAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icon-borracha.jpg"))); // NOI18N
        BOTAO_LIMPAR.setBorder(null);
        BOTAO_LIMPAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_LIMPARActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_LIMPAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        MEDIA_DIARIA_.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MEDIA_DIARIA_.setText("MÉDIA DIÁRIA");
        getContentPane().add(MEDIA_DIARIA_, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, 20));

        TEXTO_MEDIA_DIARIA.setEditable(false);
        TEXTO_MEDIA_DIARIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEXTO_MEDIA_DIARIAActionPerformed(evt);
            }
        });
        getContentPane().add(TEXTO_MEDIA_DIARIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 269, -1));

        BOTAO_PADRAO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/icon-padrao.png"))); // NOI18N
        BOTAO_PADRAO.setBorder(null);
        BOTAO_PADRAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_PADRAOActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAO_PADRAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        COMBO_DIA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        COMBO_DIA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(COMBO_DIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        OPCAO_DEFINIR_DIA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OPCAO_DEFINIR_DIA.setText("DEFINIR DIA     ");
        OPCAO_DEFINIR_DIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPCAO_DEFINIR_DIAActionPerformed(evt);
            }
        });
        getContentPane().add(OPCAO_DEFINIR_DIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        setBounds(0, 0, 613, 499);
    }// </editor-fold>//GEN-END:initComponents

    private void TEXTO_TOTAL_OLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTO_TOTAL_OLActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TEXTO_TOTAL_OLActionPerformed

    private void TEXTO_PROJETADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTO_PROJETADOActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TEXTO_PROJETADOActionPerformed
    
    private void BOTAO_RESULTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_RESULTADOActionPerformed
        // TODO add your handling code here:
        
        Calendar DIA_ATUAL = Calendar.getInstance();
        String dia_do_ano = ""+DIA_ATUAL.get(Calendar.DAY_OF_YEAR);
        
        Arquivo();//CHAMA O MÉTODO DA LEITURA DO ARQUIVO TXT
        
        BOTAO_SALVAR.setEnabled(false);//COM A OPCAO "ATUAL" DESMARCADA O BOTAO SALVAR FICA VISIVEL !
        FALTA_.setText("FALTA");
        TEXTO_FALTA.setBackground(Color.WHITE);
        
        eletronica.Meta();//CHAMA O MÉTODO QUE DEFINE A QUANTIDADE QUE DEVE SER FEITA DIARIAMENTE DE ACORDO COM O VALOR DO ARQUIVO LIDO
        notebook.Meta();
        garantia.Meta();
        desktop.Meta();
        recarga.Meta();
        impressora.Meta();
        tablet.Meta();
        laudo.Meta();
        recepcao.Meta();
        
        DATA.Data_Automatica(dia_do_ano);//CHAMA O MÉTODO QUE LER OS DIAS UTEIS PELOS ARQUIVOS TXT NOMEADOS PELOS DIAS DO ANO ...
        
        data.Dia_Atual(data.dia);//METODO DA DATA
        
        tecnico.em = Integer.parseInt(em);
        String em_tecnico = Integer.toString(tecnico.em);
        tecnico.nome = nome;
        tecnico.setor = setor;
        tecnico.porcentagem_dia_base = Double.parseDouble(porcentagem_dia_base);
        
        if(setor.equals("ELETRONICA")){
            
        indicador.eletronica = eletronica.dia*data.dias_uteis;//MULTIPLICA O N° DE MAQUINAS A SEREM FEITAS POR DIA VEZES OS DIAS ÚTEIS PASSADOS ...
	indicador.dia_base = eletronica.dia*data.dias_ate_dia_base;
        tecnico.total_ol = Double.parseDouble(total_de_ol);//RECEBE O VALOR DIGITADO
        indicador.media_diaria = tecnico.total_ol/(indicador.eletronica/eletronica.dia);
        tecnico.previsto = eletronica.dia*data.dias_uteis_totais; 
        indicador.porcentagem_total = (tecnico.total_ol/indicador.eletronica)*100;
        indicador.porcentagem_falta = (tecnico.total_ol/tecnico.previsto)*100;//*****NEW*****
	tecnico.diferenca_geral = tecnico.porcentagem_dia_base - indicador.porcentagem_total;
        
        if (tecnico.Metodo_Falta() > 0){
        TEXTO_FALTA.setText(""+tecnico.Metodo_Falta()+"     ou     "+Math.round(100-indicador.porcentagem_falta)+"%");//*****NEW***** QUANDO FALTA !!!
        }
        else
        if (tecnico.Metodo_Falta() < 0){
        TEXTO_FALTA.setBackground(Color.BLUE);
        FALTA_.setText("ACIMA");
        TEXTO_FALTA.setText(""+(tecnico.Metodo_Falta())+"     ou     "+Math.round(100-indicador.porcentagem_falta)+"%");//*****NEW*****
        }
        else
        if (tecnico.Metodo_Falta() == 0){//NA MÉDIA !!!
        TEXTO_FALTA.setBackground(Color.BLUE);
        FALTA_.setText("");
        TEXTO_FALTA.setText("100% DE APROVEITAMENTO !!!");//*****NEW*****
        }
        
        TEXTO_PREVISTO.setText(""+tecnico.previsto);
        
        if (tecnico.diferenca_geral < tecnico.porcentagem_dia_base){
        TEXTO_DIFERENCA_GERAL.setText(""+Math.round(tecnico.diferenca_geral - tecnico.diferenca_geral - tecnico.diferenca_geral)+"%");
        }
        
        TEXTO_DIA_BASE.setText(tecnico.porcentagem_dia_base+"%");
        if (indicador.porcentagem_total >= 100){TEXTO_PROJETADO.setBackground(Color.BLUE);}//MUDA COR DO PROJETADO
        else
        if ((indicador.porcentagem_total < 100) && (indicador.porcentagem_total >= 80)){TEXTO_PROJETADO.setBackground(Color.YELLOW);}
        else{TEXTO_PROJETADO.setBackground(Color.RED); }
        if (tecnico.porcentagem_dia_base >= 100){TEXTO_DIA_BASE.setBackground(Color.BLUE);}//MUDA COR DO DIA BASE
        else
        if ((tecnico.porcentagem_dia_base < 100) && (tecnico.porcentagem_dia_base >= 80)){TEXTO_DIA_BASE.setBackground(Color.YELLOW);}
        else{TEXTO_DIA_BASE.setBackground(Color.RED); }
        DecimalFormat deci = new DecimalFormat("0.00");
        TEXTO_MEDIA_DIARIA.setText(""+deci.format(indicador.media_diaria));
        if (indicador.media_diaria < eletronica.dia) {TEXTO_MEDIA_DIARIA.setBackground(Color.RED);}
        else {TEXTO_MEDIA_DIARIA.setBackground(Color.BLUE); }
            
        }
        
        else
            
        if(setor.equals("RECEPCAO")){
            
        indicador.recepcao = recepcao.dia*data.dias_uteis;//MULTIPLICA O N° DE MAQUINAS A SEREM FEITAS POR DIA VEZES OS DIAS ÚTEIS PASSADOS ...
	indicador.dia_base = recepcao.dia*data.dias_ate_dia_base;
        tecnico.total_ol = Double.parseDouble(total_de_ol);//RECEBE O VALOR DIGITADO
        indicador.media_diaria = tecnico.total_ol/(indicador.recepcao/recepcao.dia);
        tecnico.previsto = recepcao.dia*data.dias_uteis_totais; 
        indicador.porcentagem_total = (tecnico.total_ol/indicador.recepcao)*100;
        indicador.porcentagem_falta = (tecnico.total_ol/tecnico.previsto)*100;//*****NEW*****
	tecnico.diferenca_geral = tecnico.porcentagem_dia_base - indicador.porcentagem_total;
        
        if (tecnico.Metodo_Falta() > 0){
        TEXTO_FALTA.setText(""+tecnico.Metodo_Falta()+"     ou     "+Math.round(100-indicador.porcentagem_falta)+"%");//*****NEW***** QUANDO FALTA !!!
        }
        else
        if (tecnico.Metodo_Falta() < 0){
        TEXTO_FALTA.setBackground(Color.BLUE);
        FALTA_.setText("ACIMA");
        TEXTO_FALTA.setText(""+(tecnico.Metodo_Falta())+"     ou     "+Math.round(100-indicador.porcentagem_falta)+"%");//*****NEW*****
        }
        else
        if (tecnico.Metodo_Falta() == 0){//NA MÉDIA !!!
        TEXTO_FALTA.setBackground(Color.BLUE);
        FALTA_.setText("");
        TEXTO_FALTA.setText("100% DE APROVEITAMENTO !!!");//*****NEW*****
        }
        
        TEXTO_PREVISTO.setText(""+tecnico.previsto);
        
        if (tecnico.diferenca_geral < tecnico.porcentagem_dia_base){
        TEXTO_DIFERENCA_GERAL.setText(""+Math.round(tecnico.diferenca_geral - tecnico.diferenca_geral - tecnico.diferenca_geral)+"%");
        }
        
        TEXTO_DIA_BASE.setText(tecnico.porcentagem_dia_base+"%");
        if (indicador.porcentagem_total >= 100){TEXTO_PROJETADO.setBackground(Color.BLUE);}//MUDA COR DO PROJETADO
        else
        if ((indicador.porcentagem_total < 100) && (indicador.porcentagem_total >= 80)){TEXTO_PROJETADO.setBackground(Color.YELLOW);}
        else{TEXTO_PROJETADO.setBackground(Color.RED); }
        if (tecnico.porcentagem_dia_base >= 100){TEXTO_DIA_BASE.setBackground(Color.BLUE);}//MUDA COR DO DIA BASE
        else
        if ((tecnico.porcentagem_dia_base < 100) && (tecnico.porcentagem_dia_base >= 80)){TEXTO_DIA_BASE.setBackground(Color.YELLOW);}
        else{TEXTO_DIA_BASE.setBackground(Color.RED); }
        DecimalFormat deci = new DecimalFormat("0.00");
        TEXTO_MEDIA_DIARIA.setText(""+deci.format(indicador.media_diaria));
        if (indicador.media_diaria < recepcao.dia) {TEXTO_MEDIA_DIARIA.setBackground(Color.RED);}
        else {TEXTO_MEDIA_DIARIA.setBackground(Color.BLUE); }
            
        }
        
        else
            
        if(setor.equals("DESKTOP")){
            
        indicador.desktop = desktop.dia*data.dias_uteis;//MULTIPLICA O N° DE MAQUINAS A SEREM FEITAS POR DIA VEZES OS DIAS ÚTEIS PASSADOS ...
	indicador.dia_base = desktop.dia*data.dias_ate_dia_base;
        tecnico.total_ol = Double.parseDouble(total_de_ol);//RECEBE O VALOR DIGITADO
        indicador.media_diaria = tecnico.total_ol/(indicador.desktop/desktop.dia);
        tecnico.previsto = desktop.dia*data.dias_uteis_totais; 
        indicador.porcentagem_total = (tecnico.total_ol/indicador.desktop)*100;
        indicador.porcentagem_falta = (tecnico.total_ol/tecnico.previsto)*100;//*****NEW*****
	tecnico.diferenca_geral = tecnico.porcentagem_dia_base - indicador.porcentagem_total;
        
        if (tecnico.Metodo_Falta() > 0){
        TEXTO_FALTA.setText(""+tecnico.Metodo_Falta()+"     ou     "+Math.round(100-indicador.porcentagem_falta)+"%");//*****NEW***** QUANDO FALTA !!!
        }
        else
        if (tecnico.Metodo_Falta() < 0){
        TEXTO_FALTA.setBackground(Color.BLUE);
        FALTA_.setText("ACIMA");
        TEXTO_FALTA.setText(""+(tecnico.Metodo_Falta())+"     ou     "+Math.round(100-indicador.porcentagem_falta)+"%");//*****NEW*****
        }
        else
        if (tecnico.Metodo_Falta() == 0){//NA MÉDIA !!!
        TEXTO_FALTA.setBackground(Color.BLUE);
        FALTA_.setText("");
        TEXTO_FALTA.setText("100% DE APROVEITAMENTO !!!");//*****NEW*****
        }
        
        TEXTO_PREVISTO.setText(""+tecnico.previsto);
        
        if (tecnico.diferenca_geral < tecnico.porcentagem_dia_base){
        TEXTO_DIFERENCA_GERAL.setText(""+Math.round(tecnico.diferenca_geral - tecnico.diferenca_geral - tecnico.diferenca_geral)+"%");
        }
        
        TEXTO_DIA_BASE.setText(tecnico.porcentagem_dia_base+"%");
        if (indicador.porcentagem_total >= 100){TEXTO_PROJETADO.setBackground(Color.BLUE);}//MUDA COR DO PROJETADO
        else
        if ((indicador.porcentagem_total < 100) && (indicador.porcentagem_total >= 80)){TEXTO_PROJETADO.setBackground(Color.YELLOW);}
        else{TEXTO_PROJETADO.setBackground(Color.RED); }
        if (tecnico.porcentagem_dia_base >= 100){TEXTO_DIA_BASE.setBackground(Color.BLUE);}//MUDA COR DO DIA BASE
        else
        if ((tecnico.porcentagem_dia_base < 100) && (tecnico.porcentagem_dia_base >= 80)){TEXTO_DIA_BASE.setBackground(Color.YELLOW);}
        else{TEXTO_DIA_BASE.setBackground(Color.RED); }
        DecimalFormat deci = new DecimalFormat("0.00");
        TEXTO_MEDIA_DIARIA.setText(""+deci.format(indicador.media_diaria));
        if (indicador.media_diaria < desktop.dia) {TEXTO_MEDIA_DIARIA.setBackground(Color.RED);}
        else {TEXTO_MEDIA_DIARIA.setBackground(Color.BLUE); }
            
        }
        
        /////////////////////////////////////////////////////////////
        
        Double dias_rest = (data.dias_uteis_totais-data.dias_uteis);
        
        indicador.porcentagem_dias_uteis = (data.dias_uteis/data.dias_uteis_totais)*100;//*****NEW*****
        indicador.porcentagem_dias_uteis_restantes = (dias_rest/data.dias_uteis_totais)*100;//*****NEW*****
        
        String DiasUteis = Double.toString(data.dias_uteis);
        String Dias_Uteis_restantes = Double.toString(data.dias_uteis_totais-data.dias_uteis);
        
        TEXTO_DIAS_UTEIS_RESTANTES.setText(Dias_Uteis_restantes+"     ou     "+Math.round(indicador.porcentagem_dias_uteis_restantes)+"%");
        TEXTO_DIAS_UTEIS.setText(DiasUteis+"     ou     "+Math.round(indicador.porcentagem_dias_uteis)+"%");
        TEXTO_SETOR.setText(tecnico.setor);
        TEXTO_NOME.setText(tecnico.nome); 
        TEXTO_EM.setText(em_tecnico);
        TEXTO_PROJETADO.setText(""+Math.round(indicador.porcentagem_total));
        TEXTO_TOTAL_OL.setText(total_de_ol);
        
        /////////////////////////CODIGO ANTIGO/////////////////////
        
        
        if ((OPCAO_DEFINIR_DIA.isSelected()) && (OPCAO_PRODUCAO_ATUAL.isSelected()))
        {
            for(int i=0; i<1;i++)
            {
                TELA_PRINCIPAL.Mostra_Mensagem("Você não pode selecionar as duas opções simultaneamente ...", "Aviso");
            }
        }
        
        if (OPCAO_DEFINIR_DIA.isSelected())
        {
            COMBO_DIA.setEnabled(true);
            
            String DATA_DIA;
            
            int DIA = 0;
            
            DATA_DIA = (String) COMBO_DIA.getSelectedItem();
            
            DIA = Integer.parseInt(DATA_DIA);
            
            data.Dia_Atual(DIA);//METODO DA DATA
        }
        
        if (!OPCAO_DEFINIR_DIA.isSelected())
        {
            COMBO_DIA.setEnabled(false);
        }
        
        if (OPCAO_PRODUCAO_ATUAL.isSelected()){
                  
                  data.dia_do_ano += 1;
                  
                  ///////////////////////////////////////////////////////////////////////////////
                    
                  Double OL_DIA = Double.parseDouble(TEXTO_OL_DO_DIA.getText());
               
                  Double TOTAL_OL_GRAVADO = Double.parseDouble(total_de_ol);
                  
                  TEXTO_TOTAL_OL.setText(""+(TOTAL_OL_GRAVADO+OL_DIA));
                  
                  Double VALOR_PROJETADO_ATUAL = Double.parseDouble(TEXTO_PROJETADO.getText());
                  
                  Double TOTAL_PROJETADO = Double.parseDouble(porcentagem_de_producao);//TOTAL GRAVADO NO ARQUIVO ...
                  
                  TEXTO_DIFERENCA_DIARIA.setText(""+(TOTAL_PROJETADO - VALOR_PROJETADO_ATUAL));
                  
                  TEXTO_FALTA.setText(""+tecnico.Metodo_Falta()+"     ou     "+Math.round(indicador.porcentagem_falta)+"%");//*****NEW*****
                  
                  //BOTAO_SALVAR.setEnabled(false);   
                }
        
    }//GEN-LAST:event_BOTAO_RESULTADOActionPerformed

    private void TEXTO_NOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTO_NOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTO_NOMEActionPerformed

    private void TEXTO_FALTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTO_FALTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTO_FALTAActionPerformed

    private void TEXTO_PREVISTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTO_PREVISTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTO_PREVISTOActionPerformed

    private void TEXTO_DIFERENCA_GERALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTO_DIFERENCA_GERALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTO_DIFERENCA_GERALActionPerformed

    private void TEXTO_DIAS_UTEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTO_DIAS_UTEISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTO_DIAS_UTEISActionPerformed

    private void TEXTO_DIA_BASEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTO_DIA_BASEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTO_DIA_BASEActionPerformed

    private void TEXTO_EMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTO_EMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTO_EMActionPerformed

    private void BOTAO_SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_SAIRActionPerformed
        // TODO add your handling code here:
        //application.exit();
        //System.exit(0);
        this.setVisible(false); 
//Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_BOTAO_SAIRActionPerformed

    private void TEXTO_SETORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTO_SETORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTO_SETORActionPerformed

    private void TEXTO_DIAS_UTEIS_RESTANTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTO_DIAS_UTEIS_RESTANTESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTO_DIAS_UTEIS_RESTANTESActionPerformed

    private void BOTAO_SALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_SALVARActionPerformed
        
        String TotaDeOL;
        String Em;
        String Projetado;
        String OL_DO_DIA;
        
        int Q_A_OL = 0;
        int N_Q_OL = 0;
        
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        File DIRETORIO = new File("C:\\PRODUCAO");//PASTA QUE SERÁ ABERTA
        File ARQUIVO_OL = new File(DIRETORIO, "TECNICO.txt");//ARQUIVO QUE SERÁ ABERTO
        
        try {
            FileReader fileReader = new FileReader(ARQUIVO_OL);
            
            BufferedReader arq = new BufferedReader(fileReader);
            
             String  EM = arq.readLine();
             String  OL = arq.readLine();
             
             Q_A_OL = Integer.parseInt(OL);
             N_Q_OL = Integer.parseInt(TEXTO_TOTAL_OL.getText());
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        
        TotaDeOL = TEXTO_TOTAL_OL.getText();
        Em = TEXTO_EM.getText();
        Projetado = TEXTO_PROJETADO.getText();
        OL_DO_DIA = TEXTO_OL_DO_DIA.getText();
        
        ////////////////////////////////////////////////////////////////////////
        if ((TEXTO_EM.getText().equals("")))
        {
            TELA_PRINCIPAL.Mostra_Mensagem("Dados necessários em branco, por favor digite algo válido ...", "Aviso");
        }
        
        else
        if (N_Q_OL < Q_A_OL)
             {
                 
                 Object[] options = { "Sim", "Não" };   
                 int opcao = JOptionPane.showOptionDialog(null,"A quantidade de OL digitada é menor que a do registro atual"
                 +"\ntem certeza que quer alterar os dados ?","Tem certeza ?"
                 ,JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);   
  
  
                 if (opcao != 0)    
                 {
                    TELA_PRINCIPAL.Mostra_Mensagem("Você optou por não alterar as informações atuais.", "Aviso");
                 }   
              
                 if (opcao == 0)
                 {
                    
                    if (
                        1 == 1//DADOS PRIVADOS REMOVIDOS
           )
                
        {
        
        FileWriter TECNICO = null;
        
        
        try {
            TECNICO = new FileWriter("c:\\PRODUCAO\\TECNICO.txt");
            
        } catch (IOException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PrintWriter gravarArq = new PrintWriter(TECNICO);
        
        {
              gravarArq.println(Em);
              gravarArq.println(TotaDeOL);
              gravarArq.println(Projetado);
              gravarArq.println(OL_DO_DIA);
        }
        try { 
            TECNICO.close();

        } catch (IOException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        TELA_PRINCIPAL.Mostra_Mensagem(" EM: "+Em+
                                "\n TOTAL DE OL: "+TotaDeOL+
                                   "\n PROJEÇÃO: "+Projetado+"%"+
                                   "\n OL DO DIA: "+OL_DO_DIA+
                                "\n\n Informações Salvas com Sucesso.","Aviso");
        }
                 }
                 
        }
        else
        if (N_Q_OL >= Q_A_OL)
            
        {
        
        if (
            1 == 1//DADOS PRIVADOS REMOVIDOS
           )
                
        {
        
        FileWriter TECNICO = null;
        
        
        try {
            TECNICO = new FileWriter("c:\\PRODUCAO\\TECNICO.txt");
            
        } catch (IOException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PrintWriter gravarArq = new PrintWriter(TECNICO);
        
        {
              gravarArq.println(Em);
              gravarArq.println(TotaDeOL);
              gravarArq.println(Projetado);
              gravarArq.println(OL_DO_DIA);
        }
        try { 
            TECNICO.close();

        } catch (IOException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        TELA_PRINCIPAL.Mostra_Mensagem(" EM: "+Em+
                                "\n TOTAL DE OL: "+TotaDeOL+
                                   "\n PROJEÇÃO: "+Projetado+"%"+
                                   "\n OL DO DIA: "+OL_DO_DIA+
                                "\n\n Informações Salvas com Sucesso.","Aviso");
        }
        
        }
        else
        
        if (
            1 == 1//DADOS PRIVADOS REMOVIDOS
            )
                
        {
        
        FileWriter TECNICO = null;
        
        
        try {
            TECNICO = new FileWriter("c:\\PRODUCAO\\TECNICO.txt");
            
        } catch (IOException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PrintWriter gravarArq = new PrintWriter(TECNICO);
        
        {
              gravarArq.println(Em);
              gravarArq.println(TotaDeOL);
              gravarArq.println(Projetado);
              gravarArq.println(OL_DO_DIA);
        }
        try { 
            TECNICO.close();

        } catch (IOException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        TELA_PRINCIPAL.Mostra_Mensagem(" EM: "+Em+
                                "\n TOTAL DE OL: "+TotaDeOL+
                                   "\n PROJEÇÃO: "+Projetado+"%"+
                                   "\n OL DO DIA: "+OL_DO_DIA+
                                "\n\n Informações Salvas com Sucesso.","Aviso");
        }
        
        else
        
        {
            TELA_PRINCIPAL.Mostra_Mensagem("Digite um EM válido ...", "Aviso");
        }
        
    }//GEN-LAST:event_BOTAO_SALVARActionPerformed

    private void BOTAO_ATUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_ATUALActionPerformed
        // TODO add your handling code here:
        File DIRETORIO = new File("C:\\PRODUCAO");
        File ARQUIVO_OL = new File(DIRETORIO, "TECNICO.txt");
        
        try {
            FileReader fileReader = new FileReader(ARQUIVO_OL);
            
            BufferedReader arq = new BufferedReader(fileReader);
            
             String  EM = arq.readLine();
             String  OL = arq.readLine();
             String  PROJETADO = arq.readLine();
             
             TELA_PRINCIPAL.Mostra_Mensagem(" EM CADASTRADO: "+EM+
                                "\n TOTAL DE OL: "+OL+
                                   "\n PROJEÇÃO ATUAL: "+PROJETADO+"%"+
                                "\n\n","Informações Atuais");
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BOTAO_ATUALActionPerformed

    private void OPCAO_PRODUCAO_ATUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPCAO_PRODUCAO_ATUALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OPCAO_PRODUCAO_ATUALActionPerformed

    private void BOTAO_OL_DO_DIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_OL_DO_DIAActionPerformed
        // TODO add your handling code here:
        File DIRETORIO = new File("C:\\PRODUCAO");
        File ARQUIVO_OL = new File(DIRETORIO, "TECNICO.txt");
        
        try {
            FileReader fileReader = new FileReader(ARQUIVO_OL);
            
            BufferedReader arq = new BufferedReader(fileReader);
            
             String  EM = arq.readLine();
             String  OL = arq.readLine();
             String  PROJETADO = arq.readLine();
             String OL_DO_DIA = arq.readLine();
             
             TELA_PRINCIPAL.Mostra_Mensagem(" OL DO DIA: "+OL_DO_DIA,"Informações Atuais");
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BOTAO_OL_DO_DIAActionPerformed

    private void BOTAO_LIMPARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_LIMPARActionPerformed
        // TODO add your handling code here:
        TOTALDEOL.setText("TOTAL DE OL");
        OLDODIA.setText("OL DO DIA");
        FALTA_.setText("FALTA");
        TEXTO_SETOR.setText("");
        TEXTO_NOME.setText(""); 
        TEXTO_EM.setText("");
        TEXTO_PROJETADO.setText("");
        TEXTO_MEDIA_DIARIA.setText("");
        TEXTO_FALTA.setText("");
        TEXTO_PREVISTO.setText("");
        TEXTO_DIFERENCA_GERAL.setText("");
        TEXTO_DIA_BASE.setText("");
        TEXTO_TOTAL_OL.setText("");
        TEXTO_DIAS_UTEIS.setText("");
        TEXTO_DIAS_UTEIS_RESTANTES.setText("");
        TEXTO_OL_DO_DIA.setText("");
        TEXTO_DIFERENCA_DIARIA.setText("");
        TEXTO_PROJETADO.setBackground(Color.WHITE);
        TEXTO_MEDIA_DIARIA.setBackground(Color.WHITE);
        TEXTO_DIA_BASE.setBackground(Color.WHITE);
        TEXTO_FALTA.setBackground(Color.WHITE);
        //COMBO_DIA.setSelectedIndex(0);//DEFINE PARA O PRIMEIRO VALOR
        OPCAO_PRODUCAO_ATUAL.setSelected(isIcon);//DESMARCA
        OPCAO_DEFINIR_DIA.setSelected(isIcon);//DESMARCA
        COMBO_DIA.setEnabled(false);//DESATIVA DEFINIR DATA
    }//GEN-LAST:event_BOTAO_LIMPARActionPerformed

    private void TEXTO_MEDIA_DIARIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEXTO_MEDIA_DIARIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEXTO_MEDIA_DIARIAActionPerformed

    private void BOTAO_PADRAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_PADRAOActionPerformed
        // TODO add your handling code here:
        Object[] options = { "Sim", "Não" };   
                 int opcao = JOptionPane.showOptionDialog(null,"Esta opção só deve ser usada no primeiro uso do aplicativo "
                 +"\nou para zerar os dados tem certeza que deseja continuar ?","Atenção"
                 ,JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);   
  
  
                 if (opcao != 0)    
                 {
                    TELA_PRINCIPAL.Mostra_Mensagem("Você optou por não alterar as informações atuais.", "Aviso");
                 }   
              
                 if (opcao == 0)
                 {
        
        FileWriter TECNICO = null;
        
        
        try {
            TECNICO = new FileWriter("c:\\PRODUCAO\\TECNICO.txt");
            
        } catch (IOException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PrintWriter gravarArq = new PrintWriter(TECNICO);
        
        {
              gravarArq.println("0000");
              gravarArq.println("0");
              gravarArq.println("0");
              gravarArq.println("DEFALT");
              gravarArq.println("ELETRONICA");
              gravarArq.println("0");
/*
EM
TOTAL DE OL
PORCENTAGEM DE PRODUCAO TOTAL
NOME
SETOR
PORCENTAGEM DO DIA BASE
*/
        }
        try { 
            TECNICO.close();

        } catch (IOException ex) {
            Logger.getLogger(MENU_PRODUCAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        TELA_PRINCIPAL.Mostra_Mensagem("As configurações padrões do aplicativo foram gravadas com sucesso.","Aviso");
                 }
    }//GEN-LAST:event_BOTAO_PADRAOActionPerformed

    private void OPCAO_DEFINIR_DIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPCAO_DEFINIR_DIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OPCAO_DEFINIR_DIAActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
            .addKeyEventDispatcher(new KeyEventDispatcher() {
                @Override
                public boolean dispatchKeyEvent(KeyEvent event) {
                    if(event.getID() == KeyEvent.KEY_RELEASED 
                       && event.getKeyCode() == KeyEvent.VK_ENTER){
                           BOTAO_RESULTADOActionPerformed(null);
                           return true;
                     }
                     return false;
                }
        }); 
        
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
        
        COMBO_DIA.setEnabled(false);
        COMBO_DIA.setSelectedIndex(data.dia-1);//DIA 28 DEU ERRO AO ESTAR ATIVADO NO CÓDIGO ... O MOTIVO FOI NÃO HAVER TODOS OS DIAS DE 0 A 31 ...
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void BOTAO_RESULTADOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BOTAO_RESULTADOKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTAO_RESULTADOKeyPressed

    private void BOTAO_RESULTADOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BOTAO_RESULTADOKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTAO_RESULTADOKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAO_ATUAL;
    private javax.swing.JButton BOTAO_LIMPAR;
    private javax.swing.JButton BOTAO_OL_DO_DIA;
    private javax.swing.JButton BOTAO_PADRAO;
    public javax.swing.JButton BOTAO_RESULTADO;
    private javax.swing.JButton BOTAO_SAIR;
    private javax.swing.JButton BOTAO_SALVAR;
    private javax.swing.JComboBox COMBO_DIA;
    private javax.swing.JLabel DIABASE_;
    private javax.swing.JLabel DIASUTEIS;
    private javax.swing.JLabel DIASUTEIS1;
    private javax.swing.JLabel DIFERENCAGERAL;
    private javax.swing.JLabel EM_;
    private javax.swing.JLabel FALTA_;
    private javax.swing.JLabel MEDIA_DIARIA_;
    private javax.swing.JLabel NOME_;
    private javax.swing.JLabel OLDODIA;
    private javax.swing.JCheckBox OPCAO_DEFINIR_DIA;
    private javax.swing.JCheckBox OPCAO_PRODUCAO_ATUAL;
    private javax.swing.JLabel PREVISTO_;
    private javax.swing.JLabel PROJETADO_;
    private javax.swing.JLabel SETOR_;
    public javax.swing.JTextField TEXTO_DIAS_UTEIS;
    public javax.swing.JTextField TEXTO_DIAS_UTEIS_RESTANTES;
    public javax.swing.JTextField TEXTO_DIA_BASE;
    public javax.swing.JTextField TEXTO_DIFERENCA_DIARIA;
    public javax.swing.JTextField TEXTO_DIFERENCA_GERAL;
    public javax.swing.JTextField TEXTO_EM;
    public javax.swing.JTextField TEXTO_FALTA;
    public javax.swing.JTextField TEXTO_MEDIA_DIARIA;
    public javax.swing.JTextField TEXTO_NOME;
    public javax.swing.JTextField TEXTO_OL_DO_DIA;
    public javax.swing.JTextField TEXTO_PREVISTO;
    public javax.swing.JTextField TEXTO_PROJETADO;
    public javax.swing.JTextField TEXTO_SETOR;
    public javax.swing.JTextField TEXTO_TOTAL_OL;
    private javax.swing.JLabel TOTALDEOL;
    private javax.swing.JLabel TOTALDEOL2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}