/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mael
 */
public class MENU_INSPECAO extends javax.swing.JInternalFrame {

    /**
     * Creates new form MENU_INSPECAO
     */
    public MENU_INSPECAO() {
        initComponents();
        BOTAO_SALVAR.setToolTipText("Salvar");//MOSTRA MENSAGEM AO PASSAR O MOUSE EM CIMA
        BOTAO_QUANTIDADE.setToolTipText("Quantidade");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        TEXTO_OS = new javax.swing.JTextField();
        OS_ = new javax.swing.JLabel();
        TEXTO_CONFORME = new javax.swing.JTextField();
        CONFORME_ = new javax.swing.JLabel();
        BOTAO_SALVAR = new javax.swing.JButton();
        BOTAO_QUANTIDADE = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setClosable(true);
        setTitle("Inspeção");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        OS_.setText("OS:");

        CONFORME_.setText("CONFORME:");

        BOTAO_SALVAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/disquete.jpg"))); // NOI18N
        BOTAO_SALVAR.setBorder(null);
        BOTAO_SALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_SALVARActionPerformed(evt);
            }
        });

        BOTAO_QUANTIDADE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/IMAGENS/simbolo mais em verde.png"))); // NOI18N
        BOTAO_QUANTIDADE.setBorder(null);
        BOTAO_QUANTIDADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_QUANTIDADEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CONFORME_)
                    .addComponent(OS_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TEXTO_OS, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(TEXTO_CONFORME))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BOTAO_SALVAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOTAO_QUANTIDADE)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXTO_OS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OS_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXTO_CONFORME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CONFORME_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BOTAO_SALVAR)
                    .addComponent(BOTAO_QUANTIDADE))
                .addGap(202, 202, 202))
        );

        setBounds(0, 0, 410, 152);
    }// </editor-fold>//GEN-END:initComponents

    private void BOTAO_SALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_SALVARActionPerformed
        // TODO add your handling code here:
        
        java.io.File DIRETORIO = new java.io.File("C:\\PRODUCAO\\INSPECAO");
        DIRETORIO.mkdir();
        
        String OS = TEXTO_OS.getText();
        
        if(!OS.equals(""))
        
        {
        
        OS = OS+".txt";
        
        java.io.File arquivo = new java.io.File(DIRETORIO,OS );
        
        JOptionPane.showMessageDialog(null,"Informação gravada com sucesso !");
        
        try {
            arquivo.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(MENU_INSPECAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /////////////////////////
        String CONFORME;
        
        CONFORME = TEXTO_CONFORME.getText();
        
        FileWriter Conforme = null;
        try {
            Conforme = new FileWriter("C:\\PRODUCAO\\INSPECAO\\"+OS);
        } catch (IOException ex) {
            Logger.getLogger(MENU_INSPECAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        PrintWriter gravarArq = new PrintWriter(Conforme); 
        {
              gravarArq.printf(CONFORME);
        }
        try { 
            Conforme.close();
        } catch (IOException ex) {
            Logger.getLogger(MENU_INSPECAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        else
        {
            if (OS.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Campos em branco ...");
        }
        }
        
    }//GEN-LAST:event_BOTAO_SALVARActionPerformed

    private void BOTAO_QUANTIDADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_QUANTIDADEActionPerformed
        // TODO add your handling code here:
        
        File diretorio = new File("C:\\PRODUCAO\\INSPECAO\\");
        
        int quantidade = diretorio.listFiles().length;//OBTEM A QUANTIDADE DE ARQUIVOS SALVOS
        
        JOptionPane.showMessageDialog(null,"Você tem : "+quantidade+" ordens salvas.");
    
    }//GEN-LAST:event_BOTAO_QUANTIDADEActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAO_QUANTIDADE;
    private javax.swing.JButton BOTAO_SALVAR;
    private javax.swing.JLabel CONFORME_;
    private javax.swing.JLabel OS_;
    private javax.swing.JTextField TEXTO_CONFORME;
    private javax.swing.JTextField TEXTO_OS;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
