/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.AxisLocation;
import org.jfree.chart.labels.ItemLabelAnchor;
import org.jfree.chart.labels.ItemLabelPosition;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.CategoryItemRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.TextAnchor;

/**
 *
 * @author Ismael Ribeiro
 */
public class TELA_DO_GRAFICO extends javax.swing.JInternalFrame {

    /**
     * Creates new form TELA_DO_GRAFICO
     */
    public TELA_DO_GRAFICO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(980, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(374, 374, 374))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
        int[] N = new int[31];
        int[] NUM = new int[31];
        
        int MAIOR_NUMERO = 0;
        int SEGUNDO = 0;
        int TERCEIRO = 0;
        
        
        DefaultCategoryDataset Data = new DefaultCategoryDataset();
        
        int PRODUCAO_DIA_1 = 0; int QUANTIDADE_OL_DIA_1 = 0;
        int PRODUCAO_DIA_2 = 0; int QUANTIDADE_OL_DIA_2 = 0;
        int PRODUCAO_DIA_3 = 0; int QUANTIDADE_OL_DIA_3 = 0;
        int PRODUCAO_DIA_4 = 0; int QUANTIDADE_OL_DIA_4 = 0;
        int PRODUCAO_DIA_5 = 67; int QUANTIDADE_OL_DIA_5 = 2;//67 NAO ALTERAR !!!!!!!!!!!!!
        int PRODUCAO_DIA_6 = 80; int QUANTIDADE_OL_DIA_6 = 4;// 80 NAO ALTERAR !!!!!!!!!!!!!
        int PRODUCAO_DIA_7 = 86; int QUANTIDADE_OL_DIA_7 = 6;//86 NAO ALTERAR !!!!!!!!!!!!!
        int PRODUCAO_DIA_8 = 67; int QUANTIDADE_OL_DIA_8 = 6;
        int PRODUCAO_DIA_9 = 0; int QUANTIDADE_OL_DIA_9 = 0;
        int PRODUCAO_DIA_10 = 0; int QUANTIDADE_OL_DIA_10 = 0;
        int PRODUCAO_DIA_11 = 67; int QUANTIDADE_OL_DIA_11 = 8;//NAO ALTERAR
        int PRODUCAO_DIA_12 = 71; int QUANTIDADE_OL_DIA_12 = 10;
        int PRODUCAO_DIA_13 = 0; int QUANTIDADE_OL_DIA_13 = 0;
        int PRODUCAO_DIA_14 = 0; int QUANTIDADE_OL_DIA_14 = 0;
        int PRODUCAO_DIA_15 = 0; int QUANTIDADE_OL_DIA_15 = 0;
        int PRODUCAO_DIA_16 = 0; int QUANTIDADE_OL_DIA_16 = 0;
        int PRODUCAO_DIA_17 = 0; int QUANTIDADE_OL_DIA_17 = 0;
        int PRODUCAO_DIA_18 = 0; int QUANTIDADE_OL_DIA_18 = 0;
        int PRODUCAO_DIA_19 = 0; int QUANTIDADE_OL_DIA_19 = 0;
        int PRODUCAO_DIA_20 = 0; int QUANTIDADE_OL_DIA_20 = 0;
        int PRODUCAO_DIA_21 = 0; int QUANTIDADE_OL_DIA_21 = 0;
        int PRODUCAO_DIA_22 = 0; int QUANTIDADE_OL_DIA_22 = 0;
        int PRODUCAO_DIA_23 = 0; int QUANTIDADE_OL_DIA_23 = 0;
        int PRODUCAO_DIA_24 = 0; int QUANTIDADE_OL_DIA_24 = 0;
        int PRODUCAO_DIA_25 = 0; int QUANTIDADE_OL_DIA_25 = 0;
        int PRODUCAO_DIA_26 = 0; int QUANTIDADE_OL_DIA_26 = 0;
        int PRODUCAO_DIA_27 = 0; int QUANTIDADE_OL_DIA_27 = 0;
        int PRODUCAO_DIA_28 = 0; int QUANTIDADE_OL_DIA_28 = 0;
        int PRODUCAO_DIA_29 = 0; int QUANTIDADE_OL_DIA_29 = 0;
        int PRODUCAO_DIA_30 = 0; int QUANTIDADE_OL_DIA_30 = 0;
        int PRODUCAO_DIA_31 = 0; int QUANTIDADE_OL_DIA_31 = 0;
        
            N[0] = PRODUCAO_DIA_1;
            N[1] = PRODUCAO_DIA_2;
            N[2] = PRODUCAO_DIA_3;
            N[3] = PRODUCAO_DIA_4;
            N[4] = PRODUCAO_DIA_5;
            N[5] = PRODUCAO_DIA_6;
            N[6] = PRODUCAO_DIA_7;
            N[7] = PRODUCAO_DIA_8;
            N[8] = PRODUCAO_DIA_9;
            N[9] = PRODUCAO_DIA_10;
            N[10] = PRODUCAO_DIA_11;
            N[11] = PRODUCAO_DIA_12;
            N[12] = PRODUCAO_DIA_13;
            N[13] = PRODUCAO_DIA_14;
            N[14] = PRODUCAO_DIA_15;
            N[15] = PRODUCAO_DIA_16;
            N[16] = PRODUCAO_DIA_17;
            N[17] = PRODUCAO_DIA_18;
            N[18] = PRODUCAO_DIA_19;
            N[19] = PRODUCAO_DIA_20;
            N[20] = PRODUCAO_DIA_21;
            N[21] = PRODUCAO_DIA_22;
            N[22] = PRODUCAO_DIA_23;
            N[23] = PRODUCAO_DIA_24;
            N[24] = PRODUCAO_DIA_25;
            N[25] = PRODUCAO_DIA_26;
            N[26] = PRODUCAO_DIA_27;
            N[27] = PRODUCAO_DIA_28;
            N[28] = PRODUCAO_DIA_29;
            N[29] = PRODUCAO_DIA_30;
            N[30] = PRODUCAO_DIA_31;
        
            for(int i=0; i < 30; i++)
            {
                if((N[i]>MAIOR_NUMERO) && !(N[i] == 0))
                {
                    MAIOR_NUMERO = N[i];
                }
                else
                if(MAIOR_NUMERO<N[i])
                {
                    MAIOR_NUMERO = N[i];
                }
            }
        
        JOptionPane.showMessageDialog(null,"MAIOR_NUMERO: "+MAIOR_NUMERO
                                        +"\nSEGUNDO: "+SEGUNDO);
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /*if ((PRODUCAO_DIA_1 == 100) || (PRODUCAO_DIA_1 > 100))
        {
          Data.setValue(QUANTIDADE_OL_DIA_1, "Quantidade de OL", "1");Data.setValue(PRODUCAO_DIA_1, "Porcentagem de Produção de 100% em diante", "1");  
        }
        else
        if ((PRODUCAO_DIA_1 < 100) && (PRODUCAO_DIA_1 >= 80))
        {
          Data.setValue(QUANTIDADE_OL_DIA_1, "Quantidade de OL", "1");Data.setValue(PRODUCAO_DIA_1, "Porcentagem de Produção Entre 80% e 99%", "1");  
        }
        else
        if (PRODUCAO_DIA_1 < 80)
        {
          Data.setValue(QUANTIDADE_OL_DIA_1, "Quantidade de OL", "1");Data.setValue(PRODUCAO_DIA_1, "Porcentagem de Produção Abaixo de 80%", "1");
        }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        if ((PRODUCAO_DIA_2 == 100) || (PRODUCAO_DIA_2 > 100))
        {
          Data.setValue(PRODUCAO_DIA_2, "Porcentagem de Produção de 100% em diante", "2");Data.setValue(QUANTIDADE_OL_DIA_2, "Quantidade de OL", "2");  
        }
        else
        if ((PRODUCAO_DIA_2 < 100) && (PRODUCAO_DIA_2 >= 80))
        {
          Data.setValue(PRODUCAO_DIA_2, "Porcentagem de Produção Entre 80% e 99%", "2");Data.setValue(QUANTIDADE_OL_DIA_2, "Quantidade de OL", "2");  
        }
        else
        if (PRODUCAO_DIA_2 < 80)
        {
          Data.setValue(PRODUCAO_DIA_2, "Porcentagem de Produção Abaixo de 80%", "2");Data.setValue(QUANTIDADE_OL_DIA_2, "Quantidade de OL", "2");
        }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        if ((PRODUCAO_DIA_3 == 100) || (PRODUCAO_DIA_3 > 100))
        {
          Data.setValue(PRODUCAO_DIA_3, "Porcentagem de Produção de 100% em diante", "3");Data.setValue(QUANTIDADE_OL_DIA_3, "Quantidade de OL", "3");  
        }
        else
        if ((PRODUCAO_DIA_3 < 100) && (PRODUCAO_DIA_3 >= 80))
        {
          Data.setValue(PRODUCAO_DIA_3, "Porcentagem de Produção Entre 80% e 99%", "3");Data.setValue(QUANTIDADE_OL_DIA_3, "Quantidade de OL", "3");  
        }
        else
        if (PRODUCAO_DIA_3 < 80)
        {
          Data.setValue(PRODUCAO_DIA_3, "Porcentagem de Produção Abaixo de 80%", "3");Data.setValue(QUANTIDADE_OL_DIA_3, "Quantidade de OL", "3");
        }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        if ((PRODUCAO_DIA_4 == 100) || (PRODUCAO_DIA_4 > 100))
        {
          Data.setValue(PRODUCAO_DIA_4, "Porcentagem de Produção de 100% em diante", "4");Data.setValue(QUANTIDADE_OL_DIA_4, "Quantidade de OL", "4");  
        }
        else
        if ((PRODUCAO_DIA_4 < 100) && (PRODUCAO_DIA_4 >= 80))
        {
          Data.setValue(PRODUCAO_DIA_4, "Porcentagem de Produção Entre 80% e 99%", "4");Data.setValue(QUANTIDADE_OL_DIA_4, "Quantidade de OL", "4");  
        }
        else
        if (PRODUCAO_DIA_4 < 80)
        {
          Data.setValue(PRODUCAO_DIA_4, "Porcentagem de Produção Abaixo de 80%", "4");Data.setValue(QUANTIDADE_OL_DIA_4, "Quantidade de OL", "4");
        }*/
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        if ((PRODUCAO_DIA_5 == 100) || (PRODUCAO_DIA_5 > 100))
        {
          Data.setValue(PRODUCAO_DIA_5, "Porcentagem de Produção de 100% em diante", "5");Data.setValue(QUANTIDADE_OL_DIA_5, "Quantidade de OL", "5");  
        }
        else
        if ((PRODUCAO_DIA_5 < 100) && (PRODUCAO_DIA_5 >= 80))
        {
          Data.setValue(PRODUCAO_DIA_5, "Porcentagem de Produção Entre 80% e 99%", "5");Data.setValue(QUANTIDADE_OL_DIA_5, "Quantidade de OL", "5");  
        }
        else
        if (PRODUCAO_DIA_5 < 80)
        {
          Data.setValue(PRODUCAO_DIA_5, "Porcentagem de Produção Abaixo de 80%", "5");Data.setValue(QUANTIDADE_OL_DIA_5, "Quantidade de OL", "5");
        }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        if ((PRODUCAO_DIA_6 == 100) || (PRODUCAO_DIA_6 > 100))
        {
          Data.setValue(PRODUCAO_DIA_6, "Porcentagem de Produção de 100% em diante", "6");Data.setValue(QUANTIDADE_OL_DIA_6, "Quantidade de OL", "6");  
        }
        else
        if ((PRODUCAO_DIA_6 < 100) && (PRODUCAO_DIA_6 >= 80))
        {
          Data.setValue(PRODUCAO_DIA_6, "Porcentagem de Produção Entre 80% e 99%", "6");Data.setValue(QUANTIDADE_OL_DIA_6, "Quantidade de OL", "6");  
        }
        else
        if (PRODUCAO_DIA_6 < 80)
        {
          Data.setValue(PRODUCAO_DIA_6, "Porcentagem de Produção Abaixo de 80%", "6");Data.setValue(QUANTIDADE_OL_DIA_6, "Quantidade de OL", "6");
        }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        if ((PRODUCAO_DIA_7 == 100) || (PRODUCAO_DIA_7 > 100))
        {
          Data.setValue(PRODUCAO_DIA_7, "Porcentagem de Produção de 100% em diante", "7");Data.setValue(QUANTIDADE_OL_DIA_7, "Quantidade de OL", "7");  
        }
        else
        if ((PRODUCAO_DIA_7 < 100) && (PRODUCAO_DIA_7 >= 80))
        {
          Data.setValue(PRODUCAO_DIA_7, "Porcentagem de Produção Entre 80% e 99%", "7");Data.setValue(QUANTIDADE_OL_DIA_7, "Quantidade de OL", "7");  
        }
        else
        if (PRODUCAO_DIA_7 < 80)
        {
          Data.setValue(PRODUCAO_DIA_7, "Porcentagem de Produção Abaixo de 80%", "7");Data.setValue(QUANTIDADE_OL_DIA_7, "Quantidade de OL", "7");
        }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        if ((PRODUCAO_DIA_8 == 100) || (PRODUCAO_DIA_8 > 100))
        {
          Data.setValue(PRODUCAO_DIA_8, "Porcentagem de Produção de 100% em diante", "8");Data.setValue(QUANTIDADE_OL_DIA_8, "Quantidade de OL", "8");  
        }
        else
        if ((PRODUCAO_DIA_8 < 100) && (PRODUCAO_DIA_8 >= 80))
        {
          Data.setValue(PRODUCAO_DIA_8, "Porcentagem de Produção Entre 80% e 99%", "8");Data.setValue(QUANTIDADE_OL_DIA_8, "Quantidade de OL", "8");  
        }
        else
        if (PRODUCAO_DIA_8 < 80)
        {
          Data.setValue(PRODUCAO_DIA_8, "Porcentagem de Produção Abaixo de 80%", "8");Data.setValue(QUANTIDADE_OL_DIA_8, "Quantidade de OL", "8");
        }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /*if ((PRODUCAO_DIA_9 == 100) || (PRODUCAO_DIA_9 > 100))
        {
          Data.setValue(PRODUCAO_DIA_9, "Porcentagem de Produção de 100% em diante", "9");Data.setValue(QUANTIDADE_OL_DIA_9, "Quantidade de OL", "9");  
        }
        else
        if ((PRODUCAO_DIA_9 < 100) && (PRODUCAO_DIA_9 >= 80))
        {
          Data.setValue(PRODUCAO_DIA_9, "Porcentagem de Produção Entre 80% e 99%", "9");Data.setValue(QUANTIDADE_OL_DIA_9, "Quantidade de OL", "9");  
        }
        else
        if (PRODUCAO_DIA_9 < 80)
        {
          Data.setValue(PRODUCAO_DIA_9, "Porcentagem de Produção Abaixo de 80%", "9");Data.setValue(QUANTIDADE_OL_DIA_9, "Quantidade de OL", "9");
        }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        if ((PRODUCAO_DIA_10 == 100) || (PRODUCAO_DIA_10 > 100))
        {
          Data.setValue(PRODUCAO_DIA_10, "Porcentagem de Produção de 100% em diante", "10");Data.setValue(QUANTIDADE_OL_DIA_10, "Quantidade de OL", "10");  
        }
        else
        if ((PRODUCAO_DIA_10 < 100) && (PRODUCAO_DIA_10 >= 80))
        {
          Data.setValue(PRODUCAO_DIA_10, "Porcentagem de Produção Entre 80% e 99%", "10");Data.setValue(QUANTIDADE_OL_DIA_10, "Quantidade de OL", "10");  
        }
        else
        if (PRODUCAO_DIA_10 < 80)
        {
          Data.setValue(PRODUCAO_DIA_10, "Porcentagem de Produção Abaixo de 80%", "10");Data.setValue(QUANTIDADE_OL_DIA_10, "Quantidade de OL", "10");
        }*/
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        if ((PRODUCAO_DIA_11 == 100) || (PRODUCAO_DIA_11 > 100))
        {
          Data.setValue(PRODUCAO_DIA_11, "Porcentagem de Produção de 100% em diante", "11");Data.setValue(QUANTIDADE_OL_DIA_11, "Quantidade de OL", "11");  
        }
        else
        if ((PRODUCAO_DIA_11 < 100) && (PRODUCAO_DIA_11 >= 80))
        {
          Data.setValue(PRODUCAO_DIA_11, "Porcentagem de Produção Entre 80% e 99%", "11");Data.setValue(QUANTIDADE_OL_DIA_11, "Quantidade de OL", "11");  
        }
        else
        if (PRODUCAO_DIA_11 < 80)
        {
          Data.setValue(PRODUCAO_DIA_11, "Porcentagem de Produção Abaixo de 80%", "11");Data.setValue(QUANTIDADE_OL_DIA_11, "Quantidade de OL", "11");
        }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        if ((PRODUCAO_DIA_12 == 100) || (PRODUCAO_DIA_12 > 100))
        {
          Data.setValue(PRODUCAO_DIA_12, "Porcentagem de Produção de 100% em diante", "12");Data.setValue(QUANTIDADE_OL_DIA_12, "Quantidade de OL", "12");  
        }
        else
        if ((PRODUCAO_DIA_12 < 100) && (PRODUCAO_DIA_12 >= 80))
        {
          Data.setValue(PRODUCAO_DIA_12, "Porcentagem de Produção Entre 80% e 99%", "12");Data.setValue(QUANTIDADE_OL_DIA_12, "Quantidade de OL", "12");  
        }
        else
        if (PRODUCAO_DIA_12 < 80)
        {
          Data.setValue(PRODUCAO_DIA_12, "Porcentagem de Produção Abaixo de 80%", "12");Data.setValue(QUANTIDADE_OL_DIA_12, "Quantidade de OL", "12");
        }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        
        JFreeChart tipo = ChartFactory.createBarChart3D("Gráfico de Produção", "Dias","Porcentagem de Produção", Data, PlotOrientation.VERTICAL, true, true, true);
        
        final CategoryPlot plot = tipo.getCategoryPlot();
        plot.setDomainAxisLocation(AxisLocation.BOTTOM_OR_LEFT);
        plot.setRangeAxisLocation(AxisLocation.TOP_OR_LEFT);
        final CategoryItemRenderer renderer1 = plot.getRenderer(); 
                    
                    //aqui é definido o label
                    CategoryPlot plot2 = (CategoryPlot)tipo.getPlot();  
                    CategoryItemRenderer line = plot2.getRenderer();   
                    line.setBaseItemLabelGenerator(new StandardCategoryItemLabelGenerator());  
                    line.setBaseItemLabelsVisible(true);  
                    line.setBaseItemLabelPaint(java.awt.Color.BLACK);  
                    ItemLabelPosition p = new ItemLabelPosition(ItemLabelAnchor.OUTSIDE12,TextAnchor.BOTTOM_CENTER, TextAnchor.CENTER, 0.0);     
                    line.setBasePositiveItemLabelPosition(p);
                    //aqui é definido o label
        
                      renderer1.setSeriesPaint(0, java.awt.Color.gray);/////////
                      renderer1.setSeriesPaint(1, java.awt.Color.RED);/////////
                      renderer1.setSeriesPaint(2, java.awt.Color.YELLOW);/////////
                      renderer1.setSeriesPaint(3, java.awt.Color.BLUE);/////////
                      renderer1.setSeriesPaint(4, java.awt.Color.BLACK);/////////
                    
        
        try {
            
            ChartUtilities.saveChartAsJPEG(new File("C:\\PRODUCAO\\barchart.jpg"), tipo, 1340, 300);//LARGURA - ALTURA
            jLabel1.setIcon(new javax.swing.ImageIcon("C:\\PRODUCAO\\barchart.jpg")); // NOI18N
        } catch (IOException ex) {
            Logger.getLogger(TELA_DO_GRAFICO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
